exercism/configlet

.github/bin/build
.github/bin/install-build-tools
.github/workflows/build.yml

Build application in CI

---

bin/format
src/tracks.nim

Add script to format code

---

bin/release

Add release script

---

.github/bin/build
.github/bin/create-artifact
.github/workflows/build.yml

Fix macos name

---

README.md
src/cli.nim

Fix(cli): Shorten the help description of `--check`

---

tests/all_tests.nim

Refactor(all_tests): Improve import style

---

src/cli.nim

Just a small refactoring that I'd like to have in place - we'll define more error messages in the future, and it's otherwise easy to e.g. forget a quote.
There's probably a better name for this func, but I don't know what it is.
No need to create a release.
Note: the `runnableExamples` don't actually run if you run `nim doc cli.nim`, because the func isn't exported. But I've tested that they do run successfully if you add the `*` export marker to the func.
The alternatives that I'm aware of:
1. Remove the examples entirely, but then the documentation is less clear.
1. Turn the `runnableExamples` into doc comments, but then they're harder to test and thus keep in-sync with the code.
1. Move the examples into `when isMainModule` tests, and add `nim c -r cli.nim` to the CI workflow. This …

Refactor(cli): Reduce duplication in option printing

---

src/cli.nim

This PR improves how we construct the `--help` string, but does not change the actual output of `--help`.
Previously, we had to be careful with the spacing so that the help message for each option is aligned correctly.
This PR also makes it clearer that we set the name of the application in the help message at runtime, rather than compile-time.

Refactor(cli): Generate help text

---

.github/workflows/tests.yml
README.md
configlet.nimble
src/cli.nim
src/configlet.nim
src/uuid/uuid.nim
tests/all_tests.nim
tests/test_binary.nim
tests/test_uuid.nim

I included an `-n` feature, as I often wanted that.

Feature: Implement `uuid` command

---

.github/bin/build
.github/workflows/build.yml
.github/workflows/tests.yml
config.nims
tests/test_binary.nim

tests: always build fresh binary for binary tests

---

README.md

There were a few similar sentences that I probably didn't combine particularly well.
It will be easier to review the commits individually (we should squash this PR, though).

Docs(README): Improve

---

README.md
scripts/fetch-configlet
scripts/fetch-configlet.ps1

chore: remove v3 repo suffix

---

README.md

Closes https://github.com/exercism/canonical-data-syncer/issues/132

docs: update track instructions

---

.gitignore

This is useful when checking the powershell script locally.

git: ignore configlet.exe

---

src/lint/lint.nim

Maybe something like this.
I might change this to something else, but the `b1 and b2 and ...` thing was getting a bit silly.

lint: refactor conditions

---

README.md

See https://github.com/exercism/docs/pull/86

README: fix broken link to linting docs

---

src/lint/concept_exercises.nim
src/lint/concepts.nim
src/lint/lint.nim
src/lint/practice_exercises.nim
src/lint/track_config.nim
src/lint/validators.nim

lint: refactor to use common json parsing helper

---

src/lint/concept_exercises.nim
src/lint/practice_exercises.nim

Will we enable this check now?

lint: flatten authors and contributors

---

src/lint/validators.nim

This commit keeps the output of `configlet lint` the same on every track

lint(validators): support string length limit

---

src/lint/concept_exercises.nim
src/lint/practice_exercises.nim

Small improvement to readability.

lint: refactor `checkFiles` slightly

---

src/lint/concept_exercises.nim
src/lint/concepts.nim
src/lint/lint.nim
src/lint/practice_exercises.nim
src/lint/track_config.nim
src/lint/validators.nim

lint: refactor condition handling

---

src/lint/validators.nim

This commit also deduplicates some logic between `hasObject` and `isObject`.
After this, I'll:
- make the tag checking use `isString`
- deduplicate the "missing key" logic
- make `isArrayOfStrings` use `isString` internally

lint(validators): add `isString`, `isBoolean`, `isInteger`

---

src/lint/track_config.nim

This PR will be just for the second commit (https://github.com/exercism/configlet/commit/b301e63b5afd69d81dfea64be9a9eb485b18ab59)
To-do:

lint(track_config): refactor tag logic

---

src/lint/validators.nim

This improves readability.
Note that we must add the export marker to the `q` func.
---
Later I'll make our error messages more consistent, using either backticks or single quotes (rather than both).

lint(validators): use `strformat`

---

src/lint/validators.nim

The first commit here (e12a46141f8fa832ba280b5ae0a22cf6086d9937) is a proc-only implementation, but I don't love all the
```Nim
elif not isRequired:
result = true
```
and I didn't see a cleaner way to do it with e.g. a proc that takes a `var bool` parameter.
The second commit (f1bbea237f1943e4b7a95c1991220989692d3f31) is an alternative that uses a template instead.
If we make the template take a `context` parameter explicitly, I believe we can't set its default value to `""` because we'd get a compilation error like
```
template handleMissingKey(data: JsonNode; key, path: string; isRequired: bool;
context = ""; body: untyped)
first type mismatch at position: 5
required type for context: string
but expression '
result = isObject(data[key], key, path)' is of type: typed
```
But maybe we …

lint(validators): use shared logic for missing keys

---

src/lint/validators.nim

We can work out a more concise/consistent way of generating the error messages later.
This commit is a step towards implementing rules like
> The "authors" values must not have duplicates
> The "exercises.concept[].concepts" values must be non-empty, non-blank, lowercased strings using kebab-case
Where we'll be able to implement e.g. uniqueness and kebab-case checking to `isString` without implementing them a second time in `isArrayOfStrings`

lint(validators): use `isString` in `isArrayOfStrings`

---

src/lint/validators.nim

This PR will be just for the 2nd commit, e6a53c3.
To-do:

lint(validators): support HashSet check in `hasArrayOfStrings`

---

src/lint/validators.nim

There are some keys for which we want to print an error if the key is
missing, but not if the key has a value that is the empty array. This
commit gives us a way to express that.
Some relevant keys in the track `config.json` file:
- `exercises.concept` (many tracks only have Practice Exercises)
- `exercises.practice` (theoretically, a future track could have only
Concept Exercises)
- `concepts` (many tracks do not have Concepts)
---
This PR doesn't change the output of `configlet lint` on any track.
I've rebased #260 on top of this commit and updated the diff in that PR.

lint(validators): support array that is empty and required

---

src/lint/validators.nim

This isn't perfect, but it at least makes things more consistent.
Changes:
- Use only backticks, not a mix of single quotes and backticks
- Consistently write the name of the key first (I'm not convinced this is better, but it's at least a consistent style)
In a future PR:
- Add more context
- Fix some bad error messages like the
```diff
- -Not an array: root:
+The value of root is not an array:
```
This PR causes the below diff to the output of `configlet lint`
<details>
<summary>Click to expand</summary>
```diff
-String is zero-length: 'blurb':
+The value of `blurb` is a zero-length string:
-Array is empty: 'tags':
+The `tags` array is empty:
```
```diff
-String is zero-length: 'blurb':
+The value of `blurb` is a zero-length string:
-Array is empty: 'tags':
+The `tags` array is empty: …
```

lint(validators): make error wording more consistent

---

tests/all_tests.nim
tests/test_tracks.nim

Later, I'll refactor this test to avoid the string comparison.

tests(sync/tracks): add basic tests

---

src/sync/tracks.nim
tests/test_tracks.nim

Some of this is a bit opinionated, but overall I think this PR improves readability and maintainability.
The commits are atomic for your reviewing pleasure, but I'll squash this PR.
I've deliberately limited the scope of this PR mostly to the non-exported things. But I have some further changes in the pipeline.
See also: #64

sync(tracks): refactor

---

tests/test_binary.nim

This test checks that the `configlet` binary has a `generate` command
that behaves as expected for:
- A track repo without a `.md.tpl` file
- Valid placeholder syntax with an invalid slug (and without a space)
- Valid placeholder syntax with a valid slug (and without a space)
- Valid placeholder syntax with a valid slug (and with spaces)
---
This pattern of
```Nim
execAndCheck(0):
execCmdEx(cmd)
```
seems ugly to me now. Maybe I'll tweak it later to allow
```Nim
execAndCheck(cmd, 0)
```

tests(test_binary): add `generate` integration test

---

src/sync/exercises.nim
src/sync/sync.nim
src/sync/tracks.nim
tests/test_tracks.nim

Not everything here is strictly better, but it's hopefully in the right direction overall.
I've got lots more tidying up in the pipeline - the uglier changes shouldn't be here in the long-term.
This PR is part of a series that addresses #64.

sync: another refactoring pass

---

src/sync/check.nim
src/sync/exercises.nim
src/sync/sync.nim
src/sync/tracks.nim
tests/test_tracks.nim

This PR is part of a series (see #64) that tries to improve readability and
maintainability of the sync code. This PR is more superficial than the last two,
with quite a bit of bikeshedding.
For more details, please see the individual commit messages.

sync: refactor some more

---

src/lint/track_config.nim

Addressing https://github.com/exercism/docs/pull/133/files

lint(track_config): add new maxLen checks

---

src/sync/exercises.nim
tests/test_binary.nim

sync: add newline in `tests.toml` after header

---

src/lint/docs.nim
src/lint/lint.nim
src/lint/validators.nim

- lint(docs): check shared exercise docs
- lint(docs): check track docs

lint: check track and shared exercise docs

---

src/lint/track_config.nim

Improve proc names and type signatures.

lint(track_config): refactor slightly

---

src/cli.nim

This is a small refactoring-only PR.

cli: refactor

---

.github/workflows/markdownlint.yml
.markdownlint.jsonc

ci: add `markdownlint`

---

src/info/prob_specs_exercises.json

Upstream:
https://github.com/exercism/problem-specifications/commit/574c14b34021

info: add `accumulate` to deprecated exercises

---

src/lint/lint.nim

Improving readability/consistency with the style in rest of the codebase.

lint: refactor final output message

---

README.md

Feel free to suggest any other README changes in this PR.

README: improve introduction

---

src/lint/track_config.nim

- lint(track_config): check concepts with missing dir
- lint(track_config): check exercises with missing dir
According to my script, this appears to only break the `haxe` and `z3` tracks (both inactive)

lint: error on missing concept/exercise files
