exercism/configlet

- src/arguments.nim
- src/canonicaldatasyncer.nim
- src/check.nim
- src/exercises.nim
- src/logger.nim
- src/sync.nim
Feel free to suggest changes to the new names - maybe there's something better than the `ex` and `sd` prefixes I used here.
See basically any `enum` in the `nim-lang` repos:
- [Nim/compiler/options.nim](https://github.com/nim-lang/Nim/blob/fe187719abf5fa87e12e4092f87c270234fad25c/compiler/options.nim#L26-L44)
- [Nimble/src/nimblepkg/options.nim](https://github.com/nim-lang/nimble/blob/26167cd3b7671006c8bd38cbef8708431ddf8687/src/nimblepkg/options.nim#L44-L49)
- [Nim/lib/core/macros.nim](https://github.com/nim-lang/Nim/blob/cfba237d142a5ae53d593d69d6e6a560cd21863f/lib/core/macros.nim#L25-L88)
- [Nim/lib/system/io.nim](https://github.com/nim-lang/Nim/blob/cfba237d142a5ae53d593d69d6e6a560cd21863f/lib/system/io.nim#L23-L35)
- [Nim/lib/pure/os.nim](https://github.com/nim-lang/Nim/blob/cfba237d1 …
> Refactor: Remove `{.pure.}` enum annotation

- .github/bin/build
- .github/bin/linux-install-build-tools
- .github/workflows/build.yml
This PR reduces the size of the releases.
Overall: the new Linux, macOS and Windows binaries are respectively 15%, 69% and 77% of their `v0.6.0` size.
Changes:
- Build with musl on Linux
- Build with `-flto` on macOS
- Build with `--opt:size` on all platforms
I have tested on my fork that this configuration builds correctly. See [here](https://github.com/ee7/canonical-data-syncer/releases/tag/build-optimize-release).
But I haven't bumped the version, as @ErikSchierboom is doing that manually at the moment.
Size of the release archive:
|             |   Linux |   macOS | Windows |
|------------ | ------: | ------: | ------: |
| v0.6.0      | 657 KiB | 137 KiB | 115 KiB |
| This commit | 109 KiB |  95 KiB |  90 KiB |
| New / old       |    0.17 |    0.69 |    0.78 |
Size of the binary:
| …
> Build: Reduce binary size

- src/probspecs.nim
Previously, the tool did not create a `tests.toml` file for `grains`.
This PR is ugly, but it works as a hotfix.
Note that users will see the large numbers in scientific notation:
```
The following test case is missing:"
{
"uuid": "c73b470a-5efb-4d53-9ac6-c5f6487f227b",
"description": "64",
"property": "square",
"input": {
"square": 64
},
"expected": 9.223372036854776e+16
}:
Do you want to include the test case ([y]es/[n]o/[s]kip)?:
```
and
```
The following test case is missing:"
{
"uuid": "6eb07385-3659-4b45-a6be-9dc474222750",
"description": "returns the total number of grains on the board",
"property": "total",
"input": {},
"expected": 1.844674407370955e+17
}:
Do you want to include the test case ([y]es/[n]o/[s]kip)?:
```
Fixes: #39
> Fix: Add support for the `grains` exercise

- src/check.nim
Sample output, from the current state of the Tcl track:
```plain
$ ../canonical-data-syncer/canonical_data_syncer -c
Checking exercises...
... git clone output ...
[warn] list-ops: missing 1 test cases
- empty list to list (e842efed-3bf6-4295-b371-4d67a4fdf19c)
[warn] some exercises are missing test cases
```
> Check output to include missing test case descriptions

- src/probspecs.nim
Resolving a personal annoyance: get rid of the `git clone` output.
* before this change
```bash
$ ../canonical-data-syncer/canonical_data_syncer -c
Checking exercises...
Cloning into '/Users/glennjackman/src/exercism/tcl/.problem-specifications'...
remote: Enumerating objects: 540, done.
remote: Counting objects: 100% (540/540), done.
remote: Compressing objects: 100% (512/512), done.
remote: Total 540 (delta 27), reused 149 (delta 17), pack-reused 0
Receiving objects: 100% (540/540), 247.16 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (27/27), done.
[warn] list-ops: missing 1 test cases
[warn] some exercises are missing test cases
```
* after
```bash
$ ../canonical-data-syncer/canonical_data_syncer -c
Checking exercises...
[warn] list-ops: missing 1 test cases
[warn] some exercises are …
```
> Make git clone quiet

- src/probspecs.nim
PR #49 caused the program to produce no output during the `git clone` at the default verbosity setting. It was nice to remove the excessive `git clone` output, but total removal means that the program can appear to hang on a poor internet connection.
This commit makes the situation a little better for that case. In the future, we can try to improve the behaviour further.
Fixes: #52
> Fix: Show minimal `git clone` output by default

- src/check.nim
This is more efficient, and allows removal of a `sequtils` import.
> Refactor(check): Remove duplicate loop

- .github/workflows/build.yml
- canonical_data_syncer.nimble
See: https://nim-lang.org/blog/2020/10/16/version-140-released.html
I tested that this builds and releases fine on my fork. See [here](https://github.com/ee7/canonical-data-syncer/releases/tag/release-chore-bump-nim-from-1.2.6-to-1.4.0) (which is a different branch than this PR, configured to create releases on push, not tag).
Closes: #55
> Chore: Bump nim from 1.2.6 to 1.4.0

- canonical_data_syncer.nimble
- src/cli.nim
This PR adds support for separating a short option key from its value with a space (which the help message implied was possible). For example, running either of:
```
canonical_data_syncer -m include
canonical_data_syncer -m i
```
would previously produce an error:
```
Error: '-m' was given without a value
```
This is because the `parseopt` module in Nim's standard library only supports separating a short option key from its value with an equals sign, a colon, or nothing. That is, only these work:
```
canonical_data_syncer -m=include
canonical_data_syncer -m:include
canonical_data_syncer -m=i
canonical_data_syncer -m:i
canonical_data_syncer -mi
```
But a long option key and its value _can_ be separated by a space (or an equals sign, or a colon). For example:
```
canonical_data_syncer …
```
> Fix(cli): Support the syntax of e.g. `-m include`

- .github/workflows/tests.yml
- src/cli.nim
- src/probspecs.nim
- tests/all_tests.nim
- tests/config.nims
- tests/test_probspecs.nim
See the commit messages for more information - the commits are atomic.
Some things like the `git` error messages could probably be cleaned up a bit, and there's some obvious tests to add, but it should be reasonably robust. I think the implementation here is quite strict. Let me know if I missed any edge cases.
WIP:
Closes: https://github.com/exercism/canonical-data-syncer/issues/47
> Feature: Add `--probSpecsDir` option

- README.md
This should have been included in 6c603ae04e82 (#65).
> Docs: Update README.md with `-p, --probSpecsDir`

- README.md
- src/cli.nim
This makes `-o` available for `--offline`, at the cost of making `--version` solely a long option.
Decisions:
- Remove the short option from `--version`, instead of introducing case-sensitive short options (that is, uppercase `-V`).
> Fix(cli): Change `-o, --verbosity` to `-v, --verbosity`

- README.md
- src/cli.nim
- src/probspecs.nim
Motivations:
1. It allows us to establish an initial state for a `problem-specifications` directory, which means we can do black-box testing of the release binary. That is, we wouldn't be able to assert the exact outcome after running the binary if the `problem-specifications` directory is always different at the start of testing.
1. Maintainers can still use the tool even when they have no internet connection, or a very bad one.
1. Maintainers might want a "trust me, I know what I'm doing" switch so that they don't have to wait for a `git fetch`, knowing that `problem-specifications` doesn't update that often.
1. Developers of `canonical_data_syncer` can also benefit from 3 and 4.
Decisions:
- Implement this as an `--offline` flag, rather than an `--online` flag. The current …
> Feature: Add `--offline` option

- README.md
- src/cli.nim
I think this looks nicer, and a lot of my CLI tools do it too.
> Fix(cli): Align long options in help message

- src/probspecs.nim
Repo cloned with ssh does not match `github.com/exercism`
```bash
$ cd ../problem-specifications/
$ git remote -v
origin	git@github.com:exercism/problem-specifications.git (fetch)
origin	git@github.com:exercism/problem-specifications.git (push)
```
> --probSpecsDir option: Cope with ssh-cloned repo

- src/cli.nim
Most importantly, these previously invalid options are now accepted:
```
--probspecsdir
--prob-specs-dir
--prob_specs_dir
```
Before this PR, we could only use:
```
--probSpecsDir
```
That is: `--kebab-case` is now supported, even if that fact or `--prob-specs-dir` itself aren't shown in the `--help` message yet.
Note that we already had case-insensitive parsing for:
- the values for `mode`
- the values for `verbosity`
- arguments (we support `canonical_data_syncer HELP`)
Fixes: #79
> Fix(cli): Parse options insensitive to style

- src/cli.nim
- src/sync.nim
~To-do~
This PR reduces the code duplication in `cli.nim`.
The commits are atomic - please review individually. But they can be squashed before merging, if we prefer, given that they work towards the same goal.
Motivations:
- We don't need separate `parseMode` and `parseVerbosity` functions -
we can just have a generic `parseValue` proc, which is easily
extended if we ever add more options that have values.
- There should be a single source of truth for the string values of
options/values.
- This refactoring makes it easier to add support for unambiguous
abbreviations of options.
- We don't need to specify all the short options, just the short options
that we don't want to have.
> Refactor(cli): Reduce duplication

- src/cli.nim
We can do this at compile-time, rather than execution-time.
> Refactor(cli): Make `shortNoVal` and `longNoVal` const

- src/cli.nim
This proc already didn't include `probSpecsDir`, and `offline`, so let's only set the value that's different from the default (which is `verbosity` - the default is `verQuiet` since we list it first).
> Refactor(cli): Be explicit in `initConf`

- src/canonical_data_syncer.nim
- src/cli.nim
The option for using the check-only mode is `--check`, rather than `--action=check` so let's reflect that internally.
To-do:
> Refactor: Change `Action` to bool `check`

- src/cli.nim
- src/probspecs.nim
- src/tracks.nim
- tests/test_probspecs.nim
There isn't much reason to use `Option[string]` for `exercise` and `probSpecsDir` - we can just test whether the string is empty.
This also allows us to consider setting the default value of `probSpecsDir` to `.problem-specifications` in the future, which better models the current behaviour.  
Note that (both before and after this commit) if we run any of:
```
canonical_data_syncer -p=
canonical_data_syncer -p
canonical_data_syncer -e=
canonical_data_syncer -e
```
Then we see an error message like:
```
Error: '-p' was given without a value
```
> Refactor: Convert some `Option[string]` to `string`

- README.md
- src/cli.nim
- tests/test_probspecs.nim
It's more common to see kebab-case in command-line tools.
This commit only affects how the options are printed; we already parse user-provided options by normalizing for case, `-` and `_`.
Closes: #80
> Fix(cli): Display long options in kebab-case form

- .github/workflows/tests.yml
- tests/all_tests.nim
- tests/test_binary.nim
For now, this just tests some of the CLI parsing.
We should find a better way to structure the tests, because we want:
- a failing test of the binary should block a release (that doesn't happen with this PR)
- tests of the binary should run on `push` and `pull_request` (we can't just add it to `build.yml` without modification because that runs only on tagging)
https://github.com/exercism/canonical-data-syncer/blob/2ebc4f6d73adeeef4643a9e5b88a948962cf1e25/.github/workflows/build.yml#L3-L6
Maybe something like:
- move `test_binary.nim` out of `all_tests.nim`
- rename `all_tests.nim`
- make the release part of the `build.yml` workflow a separate job that depends on a testing job that runs on `push` and `pull_request`
> Test: Add initial tests for the binary

- src/cli.nim
- tests/test_binary.nim
Previously, the program would incorrectly quit with an exit code of 0 for:
- Invalid command-line parameters
- Issues with a directory specified by `-p, --prob-specs-dir`
This PR also updates the test of the binary to check exit codes.
> Fix(cli): Make `showError` quit with non-zero exit code

- src/configlet.nim
- src/logger.nim
- src/sync/check.nim
- src/sync/exercises.nim
- src/sync/probspecs.nim
- src/sync/sync.nim
- src/sync/tracks.nim
- tests/test_probspecs.nim
This will make the code easier to navigate as we add more commands.
Later on, it will be easier to identify the parts of the current `sync`
code that should be shared between commands - we can then refactor that
code and move it back to the `src` directory.
This commit also tweaks the import style, with imports in this order:
- stdlib imports
- nimble imports
- imports from another directory
- imports from the same directory
Putting square brackets around a single import is probably a bit
idiosyncratic. But maybe it helps readability to make all imports look
the same, and makes diffs less noisy later on.
I didn't move the `tests/test_probspecs.nim` file to a `tests/sync`
directory. Maybe that'd be better in the long run.
> Refactor: Use per-command src subdirectories

- scripts/fetch-configlet_v3
This makes the script more portable.
We also made this change in the `configlet` repo. See https://github.com/exercism/configlet/commit/e13f7c74c1d6840ecf92e746aa32dec12cb5febb
> fetch-configlet_v3: Use `#!/usr/bin/env bash`

- scripts/fetch-configlet_v3
Advantages of using an array here:
- It gives us a single source of truth for the options that are shared
between the `curl` commands, which is especially useful as we add more
options.
- It helps us to write the `curl` options in `--long-option` form.
- We can remove the `HEADER` variable, which would otherwise need to be
renamed when we add more headers.
Note that `curl` does not accept the syntax of `--long-option=val`.
See:
- https://google.github.io/styleguide/shellguide.html#arrays
- https://mywiki.wooledge.org/BashFAQ/050
- https://github.com/koalaman/shellcheck/wiki/SC2086
- https://github.com/koalaman/shellcheck/wiki/SC2089
Edit: See below for background on the syntax used in `('--header' "authorization: Bearer ${GITHUB_TOKEN}")`
- …
> fetch-configlet_v3: Use an array for curl options

- scripts/fetch-configlet_v3
Summary:
- Add the `-S, --show-error` flag. When combined with the existing
`-s, --silent` flag, this hides curl's progress meter without hiding
error messages.
- Add the `-f, --fail` flag. This helps to stop curl from piping
non-useful output into `grep` or `tar` in the case of failure.
See:
- https://curl.se/docs/manpage.html#-S
- https://curl.se/docs/manpage.html#-f
I believe that these flags would've helped when we were debugging the
issue that was solved by https://github.com/exercism/configlet/pull/174
> fetch-configlet_v3: Add `-Sf` flags to curl

- scripts/fetch-configlet_v3
The commit adds a header to our API request.
From the GitHub Docs:
> Important: The default version of the API may change in the future. If
> you're building an application and care about the stability of the
> API, be sure to request a specific version in the Accept header
See:
- https://docs.github.com/en/free-pro-team@latest/rest/overview/media-types
- https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-release
> fetch-configlet_v3: Request a specific GitHub API version

- scripts/fetch-configlet_v3
Oops. This is what I meant to write in https://github.com/exercism/canonical-data-syncer/pull/102.
> fetch-configlet_v3: Fix new bug in token handling

- README.md
~~This PR adds a `linting.md` document that contains the full list of linting rules that are implemented. The benefits of this are:~~
edit: the linting rules documentation has been moved to the v3-docs repo: https://github.com/exercism/v3-docs/pull/6 This PR simply links to that document now
> [Docs] Link to linting rules

- .github/bin/build
- .github/bin/create-artifact
- .github/bin/publish-release
- bin/format
- bin/release
This commit allows us to add `shellcheck` to CI in a later commit.
Changes:
- Double-quote variable expansions (resolves SC2086 shellcheck
warnings).
- Use lowercase for script-scoped variables, leaving uppercase for
environmental variables.
- Prefer `"${my_variable}"` to `"$my_variable"`.
- Resolve SC2035 warning in `bin/format`.
`shellcheck` action output after this commit:
```
Run ludeeus/action-shellcheck@master
Files: ./.github/bin/publish-release ./.github/bin/create-artifact ./.github/bin/linux-install-build-tools ./.github/bin/build ./scripts/fetch-configlet_v3 ./bin/release ./bin/format
Excluded: ! -path *./.git/* ! -path *.go ! -path */mvnw
Options: 
Status code: 0
```
And before this commit:
```
In ./.github/bin/publish-release line 3:
VERSION=$(echo $REF | cut -d "/" -f3) …
```
> build: Tidy up scripts

- README.md
> Add goal to README.md

- .github/workflows/shellcheck.yml
This causes CI to indicate failure if `shellcheck` has any complaint
about any of our scripts.
Note that we can't write
```yml
- name: Run shellcheck
uses: ludeeus/action-shellcheck@v1
```
because the `v1` tag doesn't exist, even though the latest version is `1.0.0`.
> CI: Add shellcheck workflow

- scripts/fetch-configlet_v3
Our `tar` command should contain `f -` to specify reading from stdin, as
some `tar` implementations do not read from stdin by default otherwise.
I believe the script would previously hang or fail on some platforms
(for example, some BSDs).
The script also wouldn't work on any platform that had the `TAPE`
environmental variable set.
See e.g.:
- https://www.gnu.org/software/tar/manual/html_node/file.html
- https://man.openbsd.org/tar#f
- https://unix.stackexchange.com/questions/529318
I'll also fix this in [the version of this script in the github-actions repo](https://github.com/exercism/github-actions/blob/57e87fda9c1d28cabc58f83f517aabbc59fa8c36/configlet-ci/fetch-configlet#L19)
> fetch-configlet_v3: Improve portability

- scripts/fetch-configlet_v3
The commits are atomic - please see the commit messages. (I'd prefer to squash this PR, though).
@IsaacG very kindly gave me a detailed review of the first 6 commits here and suggested the changes given by:
- https://github.com/exercism/canonical-data-syncer/commit/f393d8a7be4c5d9017d67ad9b4346830f817755c ```fetch-configlet_v3: Remove `(` in case statements```
- https://github.com/exercism/canonical-data-syncer/commit/550a4c3e8b63dd33ec3ccf77c771792c1a6d3ee5 ```fetch-configlet_v3: Prefer `[[` to `[` ```
- https://github.com/exercism/canonical-data-syncer/commit/97e852d00e1896ad5e271929e7a2ba585352161c ```fetch-configlet_v3: Move options before arguments```
The commit https://github.com/exercism/canonical-data-syncer/commit/774305f64bd5eb12618d7aaf92026074c8418164 attempts to address some …
> fetch-configlet_v3: Improve style

- scripts/fetch-configlet_v3
See https://curl.se/docs/manpage.html#--retry
> If a transient error is returned when curl tries to perform a transfer, it will retry this number of times before giving up. Setting the number to 0 makes curl do no retries (which is the default). Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408, 429 or 5xx response code.
> When curl is about to retry a transfer, it will first wait one second and then for all forthcoming retries it will double the waiting time until it reaches 10 minutes
This PR means that `curl` will request once, and if it fails, try again at 1, 2 and 4 second intervals.
> fetch-configlet_v3: Add retry to curl options

- .github/dependabot.yml
Do we want this?
---
Dependabot will now create a PR on the first day of every month for any
outdated GitHub Action that we use in a workflow.
The current list of GitHub Actions that we use is:
- actions/checkout
- jiro4989/setup-nim-action
- ludeeus/action-shellcheck
> Chore: Add dependabot

- scripts/fetch-configlet.ps1
There were quite some differences between the shell version of fetch_configlet and the powershell version. This fixes those.
- fetch-configlet: add retry count
- fetch-configlet: preserve authorization header on redirects
- fetch-configlet: stop when any error occurs
- fetch-configlet: fix authorization header not passed
- fetch-configlet: pass parameters as splat
- fetch-configlet: Use shared request options
- fetch-configlet: use pipe to simplify JSON processing
- fetch-configlet: inline if-statements
> fetch-configlet: update PowerShell version to match shell version

- .github/workflows/build.yml
- .github/workflows/shellcheck.yml
- .github/workflows/tests.yml
This PR ensures that the shellcheck and tests worflows only run on pushed to the main or master branch. This prevents duplicate execution of the workflows when a push is made to pull request. The PR also introduces support for manually triggering the workflows.
- CI: Only run shellcheck and tests on pushes to main or master branch
- CI: Allow manually triggering workflow
> [CI] Optimize workflows

- src/cli.nim
- src/configlet.nim
- src/lint/lint.nim
This PR is based off https://github.com/exercism/canonical-data-syncer/pull/106, so it should only be merged after that PR is merged.
In this PR, a minimal stub implementation of the `lint` command is added. My goals with this PR are as follows:
- Output a friendly error to tracks when they try to run `configlet lint` (which will be sooner rather than later)
- Let tracks know that we're busy implementing the linting rules and that they thus need to re-run the check regularly
- Provide a base for others to also start working on the linter. Admittedly, this doesn't help much at the moment, but it is _a_ start.
I've deliberately not added any actual linting rule implementations or tests.
> lint: Add stub implementation

- src/sync/exercises.nim
- src/sync/sync.nim
If this is approved, I'll squash this.
While working on #72 I didn't want to add a second parameter to a proc named `writeFile`, so I'd prefer to merge something like this PR first.
Feel free to bikeshed.
> sync: refactor writing of `tests.toml`

- README.md
- src/cli.nim
- src/sync/exercises.nim
- src/sync/sync.nim
- src/sync/tracks.nim
With this PR, we can now establish a beginning state by specifying:
- a track directory
- a problem-specifications directory
- the offline mode
This allows us to start doing black-box testing of the release binary, running something like:
```
configlet sync --track-dir /tmp/python --prob-specs-dir /tmp/my_prob_specs --offline
```
and then asserting that the changes made are as expected.
Closes: #50
WIP: 
Let's add tests in a later PR. We can leave `-t, --track-dir` undocumented in the first `configlet` releases if we feel it isn't tested well enough. 
Note that `--track-dir` is implemented as a global option, not an option for `sync` - the option will also be useful for e.g. `lint`.
This feature makes it much more ergonomic to implement tests for `lint`.
> Feature: Add `--trackDir` option

- scripts/fetch-configlet
While testing the `fetch-configlet` script, I found that it didn't work:
```
tar (child): -C: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
This turned out to be due to the arguments being in the wrong order.
I've also added a second commit to introduce a variable for the output directory, which makes it more concistent with the PowerShell script and reduce duplication.
> Fix fetch configlet script

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
Blog post: https://nim-lang.org/blog/2020/12/01/version-142-released.html
This also enforces that a contributor has the latest stable version of Nim installed.
With this PR:
```
$ git grep --heading --break "1\.4"
.github/workflows/build.yml
41:          nim-version: "1.4.2"
.github/workflows/tests.yml
37:          nim-version: "1.4.2"
configlet.nimble
10:requires "nim >= 1.4.2"
```
> build: bump Nim from 1.4.0 to 1.4.2

- README.md
- src/sync/probspecs.nim
This prepares for the renaming of the branches to main instead of master. We should hold off on merging this until the prob-specs repo's default branch has been renamed to `main.`
> Use main instead of master

- src/sync/exercises.nim
- src/sync/tracks.nim
Please test this with `configlet sync --track-dir some_v3_track_repo`.
Closes: #133
> sync(exercises): add `practice` to exercise path

- README.md
- src/cli.nim
This makes the repo `README` and the actual output of `configlet --help` converge.
I might squash this.
> cli: suppress options for lint

- .github/bin/build
- .github/workflows/tests.yml
- bin/release
Changes:
- Prefer `--accept` over `-y` (and erroneous uppercase `-Y`)
- Prefer `--depsOnly` over `-d`
- Move nimble options before command options
> build: make nimble options more consistent

- bin/release
I think I have a small preference for tagging without a `v` prefix.
> build: remove `v` tag prefix

- src/cli.nim
- tests/test_binary.nim
This commit also updates the tests to support a version string like
`4.0.0-alpha.1`
This commit just changes `nimble --version` output, which probably shouldn't have had a `v` in the first place. This is independent from the PR that proposes not including the `v` prefix in git tags.
> cli: remove `v` prefix from `--version` output

- .github/workflows/build.yml
- .github/workflows/shellcheck.yml
- .github/workflows/tests.yml
Perhaps most notably, this bumps the versions of gcc and musl that are
used to create the Linux release binary.
```
gcc:   7.5.0 -> 9.3.0
musl: 1.1.19 -> 1.1.24
```
We also bump the Ubuntu version in the `shellcheck.yml` and `tests.yml`
workflows.
> build: bump Ubuntu from 18.04 to 20.04

- src/configlet.nim
- src/helpers.nim
- src/lint/lint.nim
- src/sync/probspecs.nim
Extremely basic to start with.
Bad identifiers: `b1`, `b2`, `helpers`
> lint: add initial linting rules

- src/lint/lint.nim
Check if all concepts have their required files present: https://github.com/exercism/docs/blob/main/anatomy/tracks/configlet/linting.md#rule-required-files-are-present
> lint: implement concept exercise files rule

- config.nims
During development, a typical flow is to make a code change and then run
`nimble build`, which produces a debug build. However, our `config.nims`
file was enabling some optimizations for this debug build - in
particular, `--passC:-flto` adds a long wait to the linking step and
only makes sense when making a release build.
This commit makes a plain `nimble build` after no code change run in
something 1 second again, rather than something like 10 seconds (that's
actually longer than the time taken by the release build!).
Nothing is changed for the release build, which we still perform with
`nimble build -d:release`.
> build(config): make `nimble build` fast again

- .github/bin/build
- tests/test_binary.nim
It's useful for us to see the full `nimble build` output in the CI logs,
and if the build command fails in the binary tests.
> build: add `--verbose` to `nimble build`

- config.nims
This PR tries to address https://github.com/exercism/configlet/issues/16, but doesn't do so completely. The latest release of Nimble (0.12.0, in Oct 2020) adds `--hints:off` by default, and that's set after `--hint[Name]:on` can be passed.
From https://github.com/nim-lang/nimble/blob/master/changelog.markdown#0120:
> Calls to the Nim compiler now display --hints:off output by default. The --verbose flag will print the full Nim command as well as regular compiler output.
So when running `nimble build` we can only see the styleCheck output if `--verbose` was passed. However, this commit is also useful to turn on styleCheck by default for a user who runs `nim c foo.nim` in our project. 
`--styleCheck:error` would be possible too, but it's currently too
aggressive: it would currently produce …
> build(config): add `--styleCheck:hint`

- config.nims
This PR means that the Nim compiler will enforce that we don't have code like
```Nim
type
Foo = ref object
x: int
func mutate(foo: Foo) =
foo.x = 2
let foo = Foo(x: 1)
mutate(foo)
echo foo.x
```
Without strictFuncs, the above code compiles without complaint (despite `mutate` being a `func`, and `foo` being declared with `let`), and outputs `2`. But compiling with `nim c --experimental:strictFuncs`, it produces an error:
```
/tmp/foo.nim(5, 6) Error: 'mutate' can have side effects
an object reachable from 'foo' is potentially mutated
/tmp/foo.nim(6, 6) the mutation is here
```
The code should instead be written as
```diff
type
Foo = ref object
x: int
-func mutate(foo: Foo) =
+func mutate(foo: var Foo) =
foo.x = 2
-let foo = Foo(x: 1)
+var foo = Foo(x: 1)
mutate(foo)
echo foo.x
```
See:
- …
> build(config): add `--experimental:strictFuncs`

- .github/workflows/tests.yml
See https://github.com/ErikSchierboom/configlet/actions for a working example.
> ci: don't run tests when markdown files are changed

- src/lint/lint.nim
Also remove an unneeded import and fix trivial style issues.
> lint: refactor logic of finding missing files

- src/helpers.nim
- src/lint/concept_exercises.nim
- src/lint/lint.nim
- src/lint/validators.nim
WIP proof-of-concept with templates, rather than a macro as done previously.
The error messages are currently bad. I'll write more later.
> lint: begin linting concept exercise `config.json`

- src/sync/tracks.nim
The first "prepare for Exercism v3" PR on every track was merged
by 2021-02-05. This changed the track structure of every track: Exercism
v2 exercises are now "practice exercises" and have been moved to a
different path, which caused `configlet sync` to believe that all test
cases are missing.
Fixes: #174
> sync: fix for Exercism v3 track structure

- tests/test_probspecs.nim
- The first exercise of problem specs is now `accumulate`
- New problem spec has been added in https://github.com/exercism/problem-specifications/pull/1738 
- `nimble test` succeeds
- `nim c --styleCheck:error -r ./tests/all_tests.nim` succeeds
The error prior this fix was:
```
[Suite] findProbSpecsExercises: fresh clone
[OK] can return the exercises
configlet\tests\test_probspecs.nim(41, 24): Check failed: exercise.slug == "acronym"
exercise.slug was accumulate
[FAILED] the first exercise is as expected
```
> tests(probspecs): fix for `accumulate` as new first exercise

- tests/test_binary.nim
This PR tries to demonstrate that the fix in #175 is correct.
We didn't have tests for `configlet sync` yet. One reason is that they were awkward to implement until `configlet` learned the `-t, --track-dir` option, which happened relatively recently. 
Todo:
> tests(sync): add smoke test

- .gitignore
The binary tests temporarily clone the prob-specs repo and the Nim track repo. While these directories should be removed after running the tests, adding them to the .gitignore list will prevent them from being committed accidentally.
> git: ignore temporary repos used in binary tests

- src/helpers.nim
- src/lint/concept_exercises.nim
- src/lint/lint.nim
- src/lint/track_config.nim
- src/lint/validators.nim
While the template-based validator functions lead to some really nice looking code, working with them proved to be slightly harder. To keep the barrier to new contributors as low as possible, the templates have been converted to regular procs, which are easier to understand by people new to Nim.
> refactor: replace validator templates with procs

- src/cli.nim
- tests/test_binary.nim
Rationale:
- When the user writes `--help`, the help message should go to stdout.
- When the user writes some incorrect options/arguments, the help
message should go to stderr.
> console: write more things to stderr

- src/lint/validators.nim
We should have removed this line in 1bb5c115ca93 (#204).
This was our only `export` in the whole codebase. With this PR, running
```
$ git grep 'export'
```
produces no output.
> lint(validators): remove now-unused export

- src/cli.nim
- tests/test_binary.nim
Closes https://github.com/exercism/configlet/issues/200﻿
> console: write error messages to stderr

- configlet.nimble
By default, `nimble test` does this:
- find a Nim file beginning with `t` in the `tests` directory
- compile it
- run it
- repeat until all such files have been run.
But it's better to run the tests via `all_tests.nim`, which compiles
every test in one pass as an optimization. Individually compiling and
running each test file is slower because each dependency (most notably,
`system.nim`) must be compiled multiple times.
This optimization should become less important in the future - the
so-called "incremental compilation" is currently being worked on.
This commit overrides `nimble test` so that it runs the test suite the
faster way. We already ran `all_tests.nim` during CI.
Note that this commit doesn't make CI run `nimble test` for now - in CI
we currently pass `--styleCheck:error` …
> tests: make `nimble test` faster

- src/lint/validators.nim
- src/logger.nim
- src/sync/exercises.nim
- src/sync/probspecs.nim
- src/sync/tracks.nim
This PR changes `proc` to `func` where possible.
I made separate commits here, but I'd prefer to squash when merging.
> refactor: prefer `func`

- src/lint/validators.nim
For a `.meta/config.json` containing a whitespace-only string:
```json
{
"files": {
"solution": [" "],
"test": ["test_foo.nim"],
"exemplar": [".meta/exemplar.nim"]
}
}
```
Before this commit:
```
Array contains whitespace-only string: 'solution'
```
With this commit:
```
Array contains whitespace-only string: 'files.solution'
```
> lint(validators): add missing context

- src/lint/validators.nim
In our validation procs, there are conditions like
```Nim
if data.hasKey(key):
if data[key].kind == JString:
```
where the condition being `true` represents the "happy path".
To improve readability, let's try to do this consistently for every
condition apart from the innermost one; it's easier to see the "happy
path" when it minimises the number of `else`.
This commit refactors the `len` conditions accordingly, so that we
prefer `len > 0` and use `len == 0` only when there is no `else`.
This commit also changes a `var` to a `let` to better convey that we
don't mutate.
> lint(validators): refactor `len` conditions

- src/lint/concept_exercises.nim
- src/lint/concepts.nim
- src/lint/lint.nim
- src/lint/validators.nim
The validation that checked if required files were present was done in
the `lint.nim` file. To better separate concerns, these file checks have
been moved to their own modules.
The validation helper proc to check for required files has been moved to
the validators module.
--- 
This commit is from https://github.com/exercism/configlet/pull/219 - let's merge this refactoring separately, just to lower the number of commits merged as "rebase and merge" from a single PR.
> lint: extract required file checks to modules

- src/lint/lint.nim
- src/lint/practice_exercises.nim
This PR adds basic validation checks for practice exercises:
- Check if the required files are present
- Check if the .meta/config.json files are valid
The PR also applies a minor refactoring, where required file checking is moved to the corresponding module instead of the lint module.
The helper proc to check whether required files exist in a directory has been moved to the validators module to allow being called from the different modules.
> lint(validators): validate practice exercises

- src/lint/concept_exercises.nim
- src/lint/practice_exercises.nim
- src/lint/track_config.nim
- src/lint/validators.nim
So far, none of the files we were linting were an array at the top level. But `links.json` is.
Some possible future refactorings:
- Use common logic for all the "missing key" conditions.
- Make the `arrayOfStrings` procs extend the `array` procs.
- Make the empty string unnecessary in `isObject(data, "", path)`.
This PR is still a bit WIP, and I'm not set on its approach yet. But it might soon be good enough for now.
I need to do the below before I merge this PR:
> lint: support top-level array

- src/lint/concepts.nim
- src/lint/lint.nim
This PR implements [the `concept/<slug>/links.json` part of the spec](https://github.com/exercism/docs/blob/6ff54c5db80c21cb021d28d65b2528a72d9374de/building/configlet/lint.md#rule-conceptsluglinksjson-is-valid):
>- The file must be valid JSON
>- The JSON root must be an array
>- The `"[].url"` property is required
>- The `"[].url"` value must be an URL
>- The `"[].description"` property is required
>- The `"[].description"` value must be a non-empty, non-blank string
>- The `"[].icon_url"` property is optional
>- The `"[].icon_url"` value must be an URL
To-do:
> lint: add linting of concepts `links.json`

- src/lint/validators.nim
I think the case statement with
```Nim
of JNull
```
makes things more readable than
```Nim
elif data[key].kind != JNull or isRequired:
```
And maybe it's slightly better to have the ability to write targetted error messages for the `null` case. 
I've verified that this PR keeps the output of `configlet lint` the same as #199 on every track.
> lint: allow null for optional values (review)

- src/lint/validators.nim
In JSON, `null` is used to denote a value as being absent. This PR allows tracks to use `null` as the value for optional (non-required) fields.
Closes https://github.com/exercism/configlet/issues/192
> lint: allow null for optional values

- src/lint/lint.nim
Something like this could help the user fix the given linting errors.
> lint: print link to the spec on failure

- .github/workflows/build.yml
- .github/workflows/tests.yml
Changes:
- https://github.com/jiro4989/setup-nim-action/commit/1882843075f0
- https://github.com/jiro4989/setup-nim-action/commit/5f74e312d0a0
A list of our current action usage:
```
$ git grep --break --heading 'uses:'
.github/workflows/build.yml
36:        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
39:        uses: jiro4989/setup-nim-action@06254954e9ca216111b384b60904a587f1a7b22e # 1.3.1
.github/workflows/shellcheck.yml
11:        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
14:        uses: ludeeus/action-shellcheck@d586102c117f97e63d7e3b56629d269efc9a7c60 # 1.0.0
.github/workflows/tests.yml
41:        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
44:        uses: …
```
> build: bump `jiro4989/setup-nim-action` from 1.3.0 to 1.3.1

- src/cli.nim
- src/helpers.nim
Benefits:
- A user who writes `configlet lint > output.txt` will no longer see
color codes in that file.
- It becomes easier to write integration tests for `configlet lint`.
--- 
Currently when we have a PR that affects `configlet lint`, I check the diff that the PR makes to the output of `configlet lint` on every track. This PR helps to simplify that process a little.
From e.g. https://clig.dev/#output:
> Disable color if your program is not in a terminal or the user requested it. These things should disable colors:
> - `stdout` or `stderr` is not an interactive terminal (a TTY). It’s best to individually check—if you’re piping stdout to another program, it’s still useful to get colors on `stderr`.
> - The `NO_COLOR` environment variable is set.
> - The `TERM` environment variable has …
> cli,helpers: don't always use color

- src/lint/track_config.nim
From [the spec](https://github.com/exercism/docs/blob/main/building/configlet/lint.md)
> - The `"version"` key is required
> - The `"version"` value must be the integer `3`
No diff to the `configlet lint` output for the tracks - every track currently uses `3`.
In general we'll have the question "should we add this code in `track_config.nim` or `validators.nim`?"
But let's work out how best to refactor it later. And there aren't many keys where we check that an integer is a certain number or in a certain range anyway.
> lint(track_config): check `version` is `3`

- src/lint/track_config.nim
From [the spec](https://github.com/exercism/docs/blob/main/building/configlet/lint.md):
> - The `"status.concept_exercises"` key is required
> - The `"status.concept_exercises"` value must be a boolean
> - The `"status.test_runner"` key is required
> - The `"status.test_runner"` value must be a boolean
> - The `"status.representer"` key is required
> - The `"status.representer"` value must be a boolean
> - The `"status.analyzer"` key is required
> - The `"status.analyzer"` value must be a boolean
> - The `"online_editor.indent_style"` key is required
> - The `"online_editor.indent_style"` value must be the string `space` or `tab`
> - The `"online_editor.indent_size"` key is required
> - The `"online_editor.indent_size"` value must be a positive integer (>= 0)
Diff due to this PR to the …
> lint(track_config): check `status` and `online_editor`

- src/lint/track_config.nim
This commit causes the below diff to the `configlet lint` output.
```diff
+The value of `blurb` that starts with `Haxe is an open source hi...` is 423 characters, but must not exceed 400 characters:
+./config.json
+
```
---
To-do:
> lint(track_config): check `blurb` length

- src/lint/track_config.nim
To-do: 
---
This commit implements the below rules for a track's `config.json` file.
> - The `"key_features"` key is optional
> - The `"key_features"` value must be an array with length = 6
> - The `"key_features[].icon"` key is required
> - The `"key_features[].icon"` value must be a string that matches one of the pre-defined icon values (TODO: add link to list of icons)
> - The `"key_features[].title"` key is required
> - The `"key_features[].title"` value must be a non-empty, non-blank string with length <= 25
> - The `"key_features[].content"` key is required
> - The `"key_features[].content"` value must be a non-empty, non-blank string with length <= 100
See the spec:
- https://github.com/exercism/docs/blob/main/building/configlet/lint.md#rule-configjson-file-is-valid
---
Questions …
> lint(track_config): check `key_features`

- src/lint/concept_exercises.nim
- src/lint/practice_exercises.nim
This commit implements the below rules for the `.meta/config.json` file
of a Concept Exercise or a Practice Exercise.
- The `"blurb"` key is required
- The `"blurb"` value must be a non-empty, non-blank string with
length <= 350
See:
- https://github.com/exercism/docs/pull/95/files
- https://github.com/exercism/docs/blob/f7d5ec6fda07/building/configlet/lint.md
---
This PR currently makes the below diff to the `configlet lint` output, per track.
```diff
+Missing key: 'blurb':
+./exercises/practice/calculator-service/.meta/config.json
+
+Missing key: 'blurb':
+./exercises/practice/echo-service/.meta/config.json
+
+Missing key: 'blurb':
+./exercises/practice/greeting-service/.meta/config.json
+
+Missing key: 'blurb':
+./exercises/practice/hello-world-service/.meta/config.json
+
+Missing key: …
```
> lint: check `blurb` for exercises

- src/lint/practice_exercises.nim
Let's prefer `if false` over commenting out (or using `when false`).
This ensures that the code still compiles.
This commit also adds a TODO so that we can grep in the codebase for the
disabled checks.
This change also resolves the following compilation hint:
> src/lint/practice_exercises.nim(5, 6) Hint: 'checkFiles' is declared but not used [XDeclaredButNotUsed]
---
With this PR:
```
$ git grep --ignore-case --break --heading 'TODO'
src/lint/practice_exercises.nim
24:    # TODO: Enable the `files` checks after the tracks have had some time to update.
src/lint/track_config.nim
96:    # TODO: Enable the `icon` checks when we have a list of valid icons.
99:        "todo",
```
> lint(practice_exercises): prefer `if false` to commenting out

- src/lint/lint.nim
This commit adds `status`, `online_editor`, and `key_features` to the
success message.
These changes should have been included in:
- 3d19f6460d7f (#235)
- fb4712149d0a (#236)
> lint: update success message

- src/lint/track_config.nim
- src/lint/validators.nim
This simplifies the code at the call site and reduces duplication.
---
The spec contains
> The "online_editor.indent_size" value must be a positive integer (>= 0)
But do we want to limit the `indent_size` to, say, `0..8`?
This PR doesn't affect the `configlet lint` output. But the new messages would look like
```
The value of `version` is `2`, but it must be `3`:
./config.json
The value of `indent_size` is `9`, but it must be between 0 and 8 (inclusive):
./config.json
```
> lint: refactor to check value in `checkInteger`

- src/lint/track_config.nim
- src/lint/validators.nim
Similar to https://github.com/exercism/configlet/pull/244
Another refactoring is required before we can deduplicate the logic for the tags too.
---
This commit doesn't produce a diff to the current `configlet lint` output, but if it did it'd look like
```
The value of `indent_style` is `foo`, but it must be one of {"space", "tab"}:
./config.json
```
> lint: move set membership check into `checkString`

- src/lint/concepts.nim
- src/lint/validators.nim
This is a refactoring-only commit that moves validation logic into
`validators.nim`, similar to the previous two commits:
- f31e6d132fff (#245)
- 9ec79d1ac9b5 (#244)
> lint: move URL check into `checkString`

- src/lint/concepts.nim
- src/lint/track_config.nim
- src/lint/validators.nim
Continuing the idea of moving all validation logic into `validators.nim`.
> lint: move array length check

- src/lint/concept_exercises.nim
- src/lint/concepts.nim
- src/lint/practice_exercises.nim
- src/lint/track_config.nim
- src/lint/validators.nim
The `checkString`, `checkBoolean`, and `checkInteger` procs included
the `hasKey` check, so let's rename them to be consistent with
`hasArrayOf`.
> lint: rename `checkX` validators to `hasX`

- src/lint/validators.nim
This reduces the number of string allocations.
> lint(validators): prefer `isEmptyOrWhitespace` to `strip`

- src/lint/track_config.nim
PR #257 made this change possible.
This commit also improves the error message for an invalid tag.
> lint(track_config): make `tags` check use `hasArrayOfStrings`

- src/lint/track_config.nim
This is still a WIP - just showing one of the things that's in the pipeline.
Before merging this PR I need to:
For a future PR:
- Improve the error messages, and especially the context
- Implement checks for e.g. kebab-case, uniqueness, and matching
As of https://github.com/exercism/configlet/pull/260/commits/3716cf51811efd01107eb88676d6a41299681a85c, this PR currently produces the below diff to the `configlet lint` output. As I said, the error messages should be improved later.
```diff
+Missing key: 'practices':
+./config.json
+
```
```diff
+Array is empty: 'prerequisites':
+./config.json
+
```
```diff
+Array is empty: 'prerequisites':
+./config.json
+
+Configlet detected at least one problem.
+For more information on resolving the problems, please see the documentation: …
```
> lint(track_config): add initial `exercises` checks

- src/lint/track_config.nim
This PR causes the below diff to the output of `configlet lint`
```diff
+Missing key: 'concepts':
+./config.json
+
```
That is:
- all of the real tracks have a `concepts` that is at least the empty array.
- all of the tracks that have a non-empty array pass the checks.
> lint(track_config): add initial `concepts` checks

- src/lint/concept_exercises.nim
- src/lint/practice_exercises.nim
- src/lint/validators.nim
This is a step towards tidying up the context handling everywhere.
--- 
This PR keeps the output of `configlet lint` the same on every track.
We only used the non-empty string context in the `hasValidFiles` procs:
```
$ git grep --break --heading --ignore-case arrayOfStrings
```
```nim
src/lint/concept_exercises.nim
10:      hasArrayOfStrings(d, context, "solution", path),
11:      hasArrayOfStrings(d, context, "test", path),
12:      hasArrayOfStrings(d, context, "exemplar", path),
20:      hasArrayOfStrings(data, "", "authors", path),
21:      hasArrayOfStrings(data, "", "contributors", path, isRequired = false),
23:      hasArrayOfStrings(data, "", "forked_from", path, isRequired = false),
src/lint/practice_exercises.nim
10:      hasArrayOfStrings(d, context, "solution", path),
11: …
```
> lint: refactor `hasArrayOfStrings` context handling

- src/helpers.nim
- src/lint/concept_exercises.nim
- src/lint/concepts.nim
- src/lint/lint.nim
- src/lint/practice_exercises.nim
- src/lint/track_config.nim
- src/lint/validators.nim
This gives us more type safety, and helps some implementations of the
context handling. For example: it was previously possible to write
`context` and `path` in the wrong order when calling some procs, which
might go unnoticed until it affects an error message.
We can consider doing this across the whole configlet codebase, but
let's keep it within the linting code for now.
---
This PR keeps the output of `configlet lint` the same for every track.
See the [distinct type section of the Nim Manual](https://nim-lang.github.io/Nim/manual.html#types-distinct-type) for more details.
There's a couple of places where the `borrow` is a little more awkward, so I just did a `.string` for now.
We might want `context = ""` as a parameter in some proc signatures, and this PR helps.
The …
> lint: make `path` a `distinct string`

- src/lint/validators.nim
This makes it a compile-time error for one of these `call` procs to
capture a non-global variable. Our existing per-item validator procs
already had the `nimcall` calling convention, but this commit means
we'll notice if we accidentally make one into a `closure`, which has
more overhead.
This commit keeps the output of `configlet lint` the same for every 
track.
For more details, see the Nim Manual:
- https://nim-lang.org/docs/manual.html#types-procedural-type
Excerpts:
> A procedural type is internally a pointer to a procedure.
> A subtle issue with procedural types is that the calling convention of
the procedure influences the type compatibility: procedural types are
only compatible if they have the same calling convention. As a special
extension, a procedure of the calling convention …
> lint(validators): enforce `nimcall` for per-item procs

- src/lint/concept_exercises.nim
- src/lint/concepts.nim
- src/lint/practice_exercises.nim
- src/lint/track_config.nim
- src/lint/validators.nim
I'm not exactly happy with the implementation yet, but I think we can tidy it up later. And this at least produces better output.
But some of these error messages are still a bit unclear/confusing, especially the ones that are in arrays.
If we stick with the current approach, I'm leaning towards making `context` a required parameter everywhere (without a default value of `""`). I think the benefit of ensuring that we don't forget to write `context` somewhere is worth the cost of the extra verbosity at the callsite.
---
This PR produces the following diff to the output of `configlet lint`:
```diff
-The `practices` key is missing:
+The `exercises.practice.practices` key is missing:
```
```diff
-The `prerequisites` array is empty:
+The `exercises.concept.prerequisites` array is empty:
``` …
> lint: add more context in error messages

- src/lint/track_config.nim
Previously, there were some incorrect error messages because
`configlet lint` does not yet implement these rules:
> - The `"exercises.concept[].prerequisites"` value must be a non-empty
array of strings if `"exercises.concept[].status"` is not equal to
`deprecated`, except for exactly one exercise which _is_ allowed to
have an empty array as its value
> - The `"exercises.concept[].prerequisites"` value must be an empty array
if `"exercises.concept[].status"` is equal to `deprecated`
This commit temporarily allows the array to be empty.
---
This PR produces the following diff to the output of `configlet lint`
```diff
-The `exercises.concept.prerequisites` array is empty:
-./config.json
-
```
```diff
-The `exercises.concept.prerequisites` array is empty:
-./config.json
-
```
```diff
-The …
```
> lint(track_config): disable empty `prerequisites` error

- .github/workflows/build.yml
- .github/workflows/tests.yml
See:
- https://github.com/jiro4989/setup-nim-action/releases/tag/v1.3.2
- https://github.com/jiro4989/setup-nim-action/compare/06254954e9ca...d0c07f7ad4ed
---
Maybe this will fix the Windows SSL cert issue.
> build: bump `jiro4989/setup-nim-action` from 1.3.1 to 1.3.2

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
See the [release blog post](https://nim-lang.org/blog/2021/02/23/versions-144-and-1210-released.html).
---
To-do:
> build: bump Nim from 1.4.2 to 1.4.4

- src/lint/track_config.nim
- src/lint/validators.nim
- tests/all_tests.nim
- tests/test_lint.nim
This commit implements these checks for a track `config.json`:
> - The `"slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
> - The `"exercises.concept[].slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
> - The `"exercises.concept[].concepts"` values must be non-empty, non-blank, lowercased strings using kebab-case
> - The `"exercises.concept[].prerequisites"` values must be non-empty, non-blank, lowercased strings using kebab-case
> - The `"exercises.practice[].slug"` value must be a non-empty, non-blank, lowercased string using kebab-case
> - The `"exercises.practice[].practices"` values must be non-empty, non-blank, lowercased strings using kebab-case
> - The `"exercises.practice[].prerequisites"` values must be non-empty, …
> lint: add kebab-case checks

- src/lint/concepts.nim
- src/lint/track_config.nim
This resolves these compilation warnings:
>```
> ./src/lint/concepts.nim(1, 11) Warning: imported and not used: 'os' [UnusedImport]
> ./src/lint/track_config.nim(1, 11) Warning: imported and not used: 'os' [UnusedImport]
> ```
---
This issue and that in #276 snuck in because I've been using a helper script to run `nimble build` and do all the `configlet lint` diffing, and that script previously only showed the output of the `nimble build` step if it failed.
In the future we can have GitHub Actions annotations for compiler hints/warnings/errors.
> lint: remove unused imports

- src/lint/validators.nim
Previously, we didn't actually print the error (or set `result` to `false`) in `isArrayOfStrings` if the array was a non-allowed length. Oops.
Similarly to #275, this resolves these compiler hints:
> ```
> ./src/lint/validators.nim(165, 13) Hint: 'msgEnd' is declared but not used [XDeclaredButNotUsed]
> ./src/lint/validators.nim(163, 13) Hint: 'msgStart' is declared but not used [XDeclaredButNotUsed]
> ```
This PR does not affect the output of `configlet lint`. That's because we currently don't really use the `allowedArrayLen` feature of `isArrayOfStrings` / `hasArrayOfStrings`.
> lint(validators): fix array length check

- src/cli.nim
- src/configlet.nim
- src/logger.nim
- src/sync/check.nim
- src/sync/exercises.nim
- src/sync/sync.nim
- src/sync/tracks.nim
- src/uuid/uuid.nim
- tests/test_binary.nim
- tests/test_lint.nim
- tests/test_uuid.nim
The style guide now takes a position on this matter:
> Use `std` prefix for standard library modules, namely use `std/os` for
> single module and use `std/[os, sysrand, posix]` for multiple modules.
See:
- https://nim-lang.github.io/Nim/nep1.html#introduction-miscellaneous
- https://github.com/nim-lang/Nim/pull/17105/files
---
With this PR:
```
$ git grep --break --heading 'import'
```
```Nim
src/cli.nim
1:import std/[os, parseutils, strformat, strutils, terminal]
2:import pkg/cligen/parseopt3
211:    import pkg/cligen/parseopt3
src/configlet.nim
1:import std/posix
2:import "."/[cli, lint/lint, logger, sync/check, sync/sync, uuid/uuid]
src/helpers.nim
1:import std/[algorithm, os, terminal]
2:import "."/cli
src/lint/concept_exercises.nim
1:import std/[json, os]
2:import ".."/helpers …
```
> all: remove brackets from single module imports

- src/lint/track_config.nim
- src/lint/validators.nim
We should probably disable these checks (or not create a release that includes them) until we've fixed the UUIDs. Pinging @iHiD for some questions:
1. Is there a plan for replacing all the bad UUIDs written somewhere?
2. If not, will we replace the bad UUIDs at ETL-time, or should we mass PR to fix the UUIDs on the tracks in advance?
3. For the UUIDs that are shared by two tracks, will we replace them on both tracks? 
---
The output is overly verbose here - it could just say something like:
> "the track `config.json` contains the below values of `uuid`, which are not valid version 4 UUIDs".
And it could also say **why** the UUID is invalid.
However, we should probably optimise for the long-term when these errors are rare, rather than common. But that still might involve some combining of …
> lint: add offline UUID checks

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
This is a small patch release.
See:
- https://nim-lang.org/blog/2021/04/15/versions-146-and-1212-released.html
- https://github.com/nim-lang/Nim/compare/v1.4.4...v1.4.6
---
In case anybody was wondering: bumping the version in `configlet.nimble` isn't necessary, but I do it deliberately. Our codebase will likely compile with some older version, but I don't want to keep track of the lowest supported Nim version (or add earlier Nim versions to CI).
People use `configlet` as a binary, not a library, so we're just forcing `configlet` developers to have the latest stable (or a recent `devel`) version of Nim installed. That's a little annoying, but it does eliminate an entire class of issues. And it's more user-friendly than seeing errors due to old/untested Nim versions.
> build: bump Nim from 1.4.4 to 1.4.6

- README.md
The outdated README caused some problems - see https://github.com/exercism/tcl/pull/175#issuecomment-827970312
> README: update with current `tests.toml` situation

- src/lint/concept_exercises.nim
Check the `icon` property of the `.meta/config.json` file of Concept Exercises.
See https://github.com/exercism/docs/pull/123
> lint(concept_exercises): validate `icon` property

- src/lint/track_config.nim
This PR implements the rules for two new fields in the `online_editor` key:
- The `"ace_editor_language"` key is required
- The `"ace_editor_language"` value must be a non-blank string
- The `"highlightjs_language"` key is required
- The `"highlightjs_language"` value must be a non-blank string
See https://github.com/exercism/docs/pull/124/files
> lint(track_config): validate editor language properties

- src/lint/validators.nim
Some string arrays have a constraint that their values must be unique, i.e. they must not be repeated.
The `isArrayOfStrings` and `hasArrayOfStrings` functions now take a `uniqueValues` argument with which uniqueness of the array values can be enforced. The default behavior is to allow duplicate values in an array.
> lint(validators): support checking arrays for duplicates

- src/lint/concepts.nim
- src/lint/lint.nim
This PR updates `configlet lint` to reflect https://github.com/exercism/v3-launch/issues/27
As of 2021-04-02, this PR produces the below diff to the `configlet lint` output. As you'd expect, it just complains about the missing files.
<details>
<summary>Click to expand</summary>
```diff
+Missing file:
+./concepts/basics/.meta/config.json
+
+Missing file:
+./concepts/booleans/.meta/config.json
+
+Missing file:
+./concepts/conditionals/.meta/config.json
+
+Missing file:
+./concepts/floating-point-numbers/.meta/config.json
+
+Missing file:
+./concepts/lists/.meta/config.json
+
+Missing file:
+./concepts/numbers/.meta/config.json
+
+Missing file:
+./concepts/strings/.meta/config.json
+
+Missing file:
+./concepts/vectors/.meta/config.json
+
```
```diff
+Missing file: …
```
> lint: add checking of concept `.meta/config.json`

- src/sync/exercises.nim
- src/sync/probspecs.nim
- src/sync/tracks.nim
Reasons:
- It works for both `object` and `ref object`. For the latter, we can
remove the call to `new` - it is invoked implicitly for `ref object`.
- It's easier for the compiler to prove that an object has been fully
initialized.
- It's arguably more readable.
---
See https://github.com/exercism/configlet/issues/64
> sync: prefer the object construction syntax

- src/sync/exercises.nim
- src/sync/tracks.nim
From the [Nim standard library style guide](https://nim-lang.github.io/Nim/nep1.html#introduction-naming-conventions):
> `initFoo` initializes a value type `Foo`
> `newFoo`: initializes a reference type `Foo` via `new` or a value type `Foo` with reference semantics.
However, in the generated code, any object bigger than 24 bytes is
actually passed by reference. Therefore we don't need to think about
performance when deciding between `object` and `ref object`.
Note that `newSeq` and `newString` were named before Nim had this naming
convention - they do not comply with it. That is, `string` and `seq`
each have value semantics by default (an assignment creates a copy).
See also: #64
> sync: prefer `init` for initializing non-ref objects

- .github/workflows/tests.yml
`--styleCheck:error` is useful because it makes a identifier naming
inconsistency cause a failing CI check. However, it also checks the
identifier naming in dependencies, such as the Nimble packages that we
import. This has become too inconvenient.
This commit alters our CI to use `nimble test`, which effectively moves
us back to `--styleCheck:hint` (as specified by our `config.nims` file).
The development version of Nim has a new CLI option that allows turning
a hint into an error. That is, in the future we could use
`--hintAsError[Name]:on` to get the best of both worlds.
> ci: use `--styleCheck:hint` not `--styleCheck:error`

- scripts/fetch-configlet
- scripts/fetch-configlet.ps1
This PR adds a comment to the `scripts/fetch-configlet` and `scripts/fetch-configlet.ps1` files to help track maintainers understand that they shouldn't directly change these files in their track's repository, but instead change the upstream source.
Closes https://github.com/exercism/configlet/issues/285
> fetch-configlet: add comment with upstream location

- src/sync/exercises.nim
- tests/test_binary.nim
Some suggestions for #317.
Changes:
- Make the tests pass.
- Add some parens. This is an opinionated change, and isn't a strict improvement in readability. But I think it helps make the codebase more reader-friendly when done consistently. It also currently improves the syntax highlighting on GitHub and in many editors.
- Bikeshed comment - I didn't love "output" and "value" because it could sound like it addresses https://github.com/exercism/configlet/issues/61, but we'll address that elsewhere.
> review: "sync: output reimplements property (#317)"

- src/lint/validators.nim
The `.meta/config.json` file of Concept and Practice Exercises contains a
`files` property, which contains the (relative) path to the various files
of the exercise. This PR adds a `hasArrayOfFiles` function that:
1. Check if the property is a string array using `hasArrayOfStrings`
2. For each string value, prepend that value with the exercise dir
and check if a file exists at that path
> lint(validators): support checking exercise file paths

- src/lint/concept_exercises.nim
- src/lint/practice_exercises.nim
This PR implements the below checks for each exercise's
`.meta/config.json` file.
- The files listed in the "files.solution" array must exist
- The files listed in the "files.test" array must exist
- The files listed in the "files.exemplar" array must exist
- The files listed in the "files.example" array must exist
> lint: check file paths in exercise `.meta/config.json` files

- tests/test_tracks.nim
We refactored `sync/tracks.nim` to remove a non-exported field from the
`TrackExercise` object. Therefore we can now simplify the test like
this, without changing field/type visibility just for the purpose of
testing.
> tests(sync/tracks): compare objects, not strings

- scripts/fetch-configlet
This PR:
1. Removes space before some parentheses to be more consistent with 
```
get_download_url() {
```
2. Prefer `==` to `=` inside `[[ ]]`
From https://google.github.io/styleguide/shellguide.html#testing-strings
> For clarity, use `==` for equality rather than `=` even though both
> work. The former encourages the use of `[[` and the latter can be
> confused with an assignment.
> fetch-configlet: tweak style

- README.md
We now have a GitHub issue that tracks the currently implemented linting
rules, but still shows the entirety, so let's link to that instead.
> README: prefer link to linting checklist

- .gitignore
This helps to reduce the noise in `git status` for a `configlet`
contributor who, for example:
- wants to compile some already committed Nim files individually, and
sometimes uses `nim c -r` rather than `nim r`.
- has created some files that should be available on any branch, and so
are kept uncommitted.
---
Let's just say that even **with** this PR, on my machine:
```
$ git status -s | wc -l
78
```
So this helps a bit.
> git: ignore all binaries

- src/sync/tracks.nim
This PR tries to improve the error message for:
- a missing `exercises` key in a track `config.json` file
- a missing track `config.json` file
> sync(tracks): improve some error messages

- src/cli.nim
- src/configlet.nim
- src/generate/generate.nim
- src/helpers.nim
- src/lint/validators.nim
This PR adds basic support for the `generate` command: https://github.com/exercism/docs/blob/main/building/configlet/generating-documents.md
I'd really appreciate feedback on the code to see if there is anything wrong with it.
For now, I've decided to remove the level one heading from the Concept's `introduction.md` file when including it in the generated `introduction.md` file, as tracks might not want multiple level one headings. Also, a lot of the Concept `introduction.md` files have `# Introduction` as their starting (totally valid) level one heading, which would look really weird.
This PR currently does not support only generate the `introduction.md` for a single exercise, due to the inability to share properties within a `case`. This will be supported in a future version of Nim, but …
> generate: add `generate` command

- src/lint/track_config.nim
- src/lint/validators.nim
With this commit, `configlet lint` now checks the below rules for a
track's root `config.json` file.
- The `test_runner.average_run_time` key is required if
`status.test_runner` is equal to `true`
- The `test_runner.average_run_time` value must be a floating-point
number > 0 with one decimal point of precision
---
The requirement for
> "with one decimal point of precision"
is quite painful, since it requires parsing the value as a string.
---
Some sample error messages for bad values:
```
The value of `test_runner.average_run_time` is 3., but it must have exactly 1 digit after the decimal point:
./config.json
The value of `test_runner.average_run_time` is 3.00, but it must have exactly 1 digit after the decimal point:
./config.json
The value of `test_runner.average_run_time` is -0.1, but …
```
> lint: check `test_runner.average_run_time`

- src/lint/track_config.nim
- src/lint/validators.nim
This PR adds the new linting rules from https://github.com/exercism/docs/pull/127
With this commit, `configlet lint` now checks the following rules for a
track-level `config.json` file:
- The `exercises.foregone` values must not have duplicates
- The `tags` values must not have duplicates
And these rules for a Concept Exercise `config.json` file:
- The `files.solution` values must not have duplicates
- The `files.test` values must not have duplicates
- The `files.exemplar` values must not have duplicates
And these rules for a Practice Exercise `config.json` file:
- The `files.solution` values must not have duplicates
- The `files.test` values must not have duplicates
- The `files.example` values must not have duplicates
---
This PR currently keeps the output of `configlet lint` the same …
> lint: require more arrays to have unique values

- src/sync/exercises.nim
- src/sync/probspecs.nim
- src/sync/sync.nim
- tests/test_probspecs.nim
This PR is part of a series that addresses #64.
I've verified that this commit keeps the output of
`configlet sync --check` the same on every track.
This PR is currently a 3–⁠5x speedup, depending on the track.
Measuring the execution time of
```
./configlet sync --check --offline --probSpecsDir=/path/to/local/problem-specifications
```
in different track repos, before and after this PR:
|        |    ada |    nim |   csharp |
| ------ | -----: | -----: | -------: |
| Before | 100 ms | 110 ms |   120 ms |
| After  |  20 ms |  35 ms |    40 ms |
It wasn't particularly slow before for the end-user, but it was
noticeable when running `configlet sync --check` on every track for
regression testing).
An upcoming commit will optimize further: currently we parse every
`canonical-data.json` file …
> sync(probspecs): refactor

- src/sync/exercises.nim
- src/sync/probspecs.nim
- tests/test_probspecs.nim
Running `configlet sync` would previously parse every
`canonical-data.json` file in the problem-specifications repo as the
first step. There are currently 119 of these files, and the execution
time of an offline `configlet sync --check` is usually dominated by JSON
parsing.
With this commit, we only parse a `canonical-data.json` file if the
track implements the corresponding exercise - this is a worthwhile
speedup for tracks that implement only a small fraction of the exercises
in `problem-specifications`.
This commit also reduces the binary size by 10% (at least for the
Linux one).
Measuring the execution time of
```
configlet sync --check --offline --prob-specs-dir=path/to/problem-specifications
```
in different track repos, before and after this commit:
|                 | …
> sync: don't parse unneeded `canonical-data.json` files

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
See [blog post](https://nim-lang.org/blog/2021/05/25/version-148-released.html) and https://github.com/nim-lang/Nim/compare/v1.4.6...v1.4.8
Showing all the places where we have the Nim version:
```
$ git grep --break --heading '1\.4'
.github/workflows/build.yml
41:          nim-version: "1.4.8"
.github/workflows/tests.yml
46:          nim-version: "1.4.8"
configlet.nimble
10:requires "nim >= 1.4.8"
```
> build: bump Nim from 1.4.6 to 1.4.8

- src/lint/track_config.nim
With the switch to CodeMirror as the online editor library, the
`online_editor.ace_editor_language` key is now obsolete and its presence
should not be checked anymore. This PR removes that check.
> lint: remove ace_editor_language check

- README.md
- src/sync/exercises.nim
- tests/test_binary.nim
This commits adds a `reimplements` property to the `tests.toml` file to help identify re-implemented test cases:
```toml
[b9228bb1-465f-4141-b40f-1f99812de5a8]
description = "disallow first strand longer"
reimplements = "919f8ef0-b767-4d1b-8516-6379d07fcb28"
```
Closes https://github.com/exercism/configlet/issues/316
@ee7 This was suggested during one of the weekly meetups, and I thought it made sense. I've create a small PoC. Let me know what you think.
> sync: output `reimplements` property

- tests/test_binary.nim
This commit updates our tests of the configlet binary to use the latest
problem-specifications commit. Reason: we want the update that removes
unnecessary nesting [1] before we make configlet write each `tests.toml`
test case `description` to show the nesting.
[1] https://github.com/exercism/problem-specifications/pull/1798/files
---
After merging this, I'll rebase #301 on top of `main`.
> tests(binary): update `problem-specifications` hash

- src/sync/probspecs.nim
- tests/test_binary.nim
Some problems defined in the problem-specifications repo are defined using nesting. configlet handles these nicely, but the description of the `tests.toml` files only contains the description of the test case itself, which can be confusing if test cases in different nested objects have the same description.
This PR writes the full description to the `tests.toml` file. For example, `Test group description → Test case description` for a singly-nested test case.
Closes https://github.com/exercism/configlet/issues/202
While working on this PR, I found that there are two exercises that contain unneeded nesting: https://github.com/exercism/problem-specifications/pull/1798 I've deferred updating the tests until after that PR has been merged, to prevent unnecessary work.
> sync: output full description for nested test cases

- tests/test_binary.nim
Before running our tests of the configlet executable, our setup
automatically builds configlet (so that we don't forget).
We should test an executable that is as close as possible to that we
distribute, which means we should build with the same compilation flags.
However, a debug build should usually produce the same test status -
with this commit, we perform the longer build only during CI so that
running the tests locally is faster.
> tests(binary): speed up local testing

- src/sync/probspecs.nim
- tests/test_binary.nim
Follow-up from https://github.com/exercism/configlet/pull/301#pullrequestreview-673890680:
> Okay, I'll merge then. I'll make a follow-up PR later for the delimiter bikeshedding.
> 
> It's just that I want to avoid a mass PR that updates every `→` to e.g. `->` on every track. And I think that we should consider making a mass PR that adds `reimplements`, the fuller `description`, and the new comment at the top of every `tests.toml`. This would better explain how `tests.toml` works, and prevent noisy diffs in the first PR for every track exercise that touches the corresponding `tests.toml`.
> 
> So if we do want such a mass PR, I think we should settle the delimiter decision and the `tests.toml` comment wording first. We might also want to settle these things before creating the next …
> sync: change `description` nesting arrow

- README.md
- src/sync/exercises.nim
- tests/test_binary.nim
Follow-up from https://github.com/exercism/configlet/pull/317#pullrequestreview-671985491
I think it's pretty hard to find a great wording here. Any suggestions?
Summary:
- Don't say "update" - we recreate a `description`, even if the `tests.toml` lacked it.
- Mention `configlet sync`, so that people don't think of `configlet generate`
- Say "key/value pair", rather than "property" (which I think is incorrect terminology for TOML)
- Explicitly say that `include = true` is implied
I'll update this PR to fix the tests later.
> sync: improve `tests.toml` comment

- src/sync/sync.nim
See the commit messages.
Thoughts?
In the future, this is an area where I'd like to add color for clarity (potentially with syntax highlighting for JSON) - I've opened #353.
```
Syncing exercises...
Cloning the problem-specifications repo into /foo/.problem-specifications...
[warn] anagram: missing 1 test cases
The following test case is missing:"
{
"uuid": "03eb9bbe-8906-4ea0-84fa-ffe711b52c8b",
"reimplements": "b3cca662-f50a-489e-ae10-ab8290a09bdc",
"comments": [
"Reimplemented to be consistent about removing references to 'master'"
],
"description": "detects two anagrams",
"property": "findAnagrams",
"input": {
"subject": "solemn",
"candidates": [
"lemons",
"cherry",
"melons"
]
},
"expected": [
"lemons",
"melons"
]
}:
It reimplements this test case:
{
"uuid": …
```
> sync: improve readability in interactive mode

- README.md
- src/cli.nim
- src/configlet.nim
- src/sync/update.nim
- tests/test_binary.nim
First step towards https://github.com/exercism/configlet/issues/298
---
To-do:
> It will then prompt the user to choose whether to include or exclude missing tests, and update the `tests.toml` files accordingly. If you only want a quick check, you can use the `--check` option.
> sync: remove `--check` and add `--update`

- README.md
This PR:
- documents `configlet uuid`
- syncs the help message in the README with `configlet --help` (`generate` was missing).
I didn't add the docs for `configlet generate` yet. Could you suggest some, @ErikSchierboom?
> README: document `uuid` and `generate`

- src/sync/exercises.nim
Under some circumstances, we previously parsed `tests.toml` once per test case (!).
> sync(exercises): remove duplicate `tests.toml` parsing

- .gitignore
- tests/test_binary.nim
This PR makes re-running the end-to-end tests much saner/faster. Without this change (or commenting-out the `git clone` lines), it's painful to add tests.
See the commit messages.
I was going to push these changes (and much more upcoming) to #366, but it makes that PR (and eventual squashed commit) too large - it'll already be pretty big. So I want to merge a few PRs first - this won't slow things down more. I consider adding decent tests one of the biggest parts of #366, so in this case I want to not hate the initial state of the new tests.
The next PR will improve the cloning process further, so we'll just have `setupExercismRepo` at the call site that does "clone if necessary, and checkout".
I think I've finally figured out an ergonomic design for some exec/git helper commands, so …
> tests(binary): improve cloning

- src/exec.nim
- tests/test_binary.nim
- tests/test_probspecs.nim
- tests/test_tracks.nim
This PR is a follow-up of #379, where I wrote:
> I was going to push these changes (and much more upcoming) to #366, but it makes that PR (and eventual squashed commit) too large - it'll already be pretty big. So I want to merge a few PRs first - this won't slow things down more. I consider adding decent tests one of the biggest parts of #366, so in this case I want to not hate the initial state of the new tests.
> The next PR will improve the cloning process further, so we'll just have `setupExercismRepo` at the call site that does "clone if necessary, and checkout".
> I think I've finally figured out an ergonomic design for some exec/git helper commands, so they'll soon infect the rest of our codebase too.
See the individual commits.
The hard question: can we think of a better name than …
> tests: refactor to share code for exec and git

- tests/test_binary.nim
Tiny PR. This gives a configlet developer a shortcut (`nim r -d:skipBuild test_binary`) for re-running the end-to-end tests after making changes to them alone.
This is fine as a compile-time flag, rather than a run-time flag.
> tests(binary): support skipping build

- src/lint/track_config.nim
This commit enables checking the key feature icons against the list of
allowed icons.
See also:
- https://github.com/exercism/docs/pull/186, which defines the list of
key feature icons
> lint(track_config): check key feature icons

- src/lint/track_config.nim
This commit adds four missing key feature icons:
- `evolving`
- `immutable`
- `stable`
- `web`
See also:
- https://github.com/exercism/docs/pull/187, which adds these icons to
the list of key feature icons
> lint(track_config): add missing key feature icons

- src/lint/concept_exercises.nim
- src/lint/concepts.nim
- src/lint/practice_exercises.nim
- src/lint/track_config.nim
- src/lint/validators.nim
Fixes https://github.com/exercism/configlet/issues/395
To-do:
This PR currently produces the below diff to the output of `configlet lint`, per track.
<details>
<summary>Click to expand</summary>
```diff
-The value of `key_features.icon` is root, but it must be one of the allowed values:
+The value of `key_features.icon` is the empty string, but it must be one of the allowed values:
-The value of `key_features.icon` is root, but it must be one of the allowed values:
+The value of `key_features.icon` is the empty string, but it must be one of the allowed values:
-The value of `key_features.icon` is root, but it must be one of the allowed values:
+The value of `key_features.icon` is the empty string, but it must be one of the allowed values:
-The value of `key_features.icon` is root, but it …
```
> lint(validators): improve message for empty string

- tests/test_binary.nim
This just indents the contents of triple quoted string literals in `tests/test_binary.nim`, which makes the tests easier to follow visually.
Example before this PR:
```Nim
test "after syncing, another `sync --update --mode=include` performs no changes":
execAndCheck(0):
execCmdEx(&"{binaryPath} -t {trackDir} sync --update -mi -o -p {psDir}")
check outp == """
Syncing exercises...
All exercises are synced!
"""
test "after syncing, a `sync` without `--update` shows that exercises are up to date":
execAndCheck(0):
execCmdEx(&"{binaryPath} -t {trackDir} sync -o -p {psDir}")
check outp == """
Checking exercises...
All exercises are up-to-date!
"""
```
With this PR:
```Nim
test "after syncing, another `sync --update --mode=include` performs no changes":
execAndCheck(0):
execCmdEx(&"{binaryPath} …
```
> tests(binary): improve readability of multi-line string literals

- configlet.nimble
- src/lint/track_config.nim
With this commit, `configlet lint` now checks the below rules for a
track-level `config.json` file:
- The `exercises.concept[].prerequisites` values must match any other
concept exercise's `concepts` property values
- The `exercises.concept[].prerequisites` values must not match any of
the values in the exercise's `exercises.concept[].concepts` property
---
Quick hack for https://github.com/exercism/exercism/issues/5770
Ping @iHiD 
See also:
- https://github.com/exercism/rust/issues/1303
---
At the time of writing, this PR produces exactly the following diff to the output of `configlet lint`, per track:
```diff
+The Concept Exercise `savings-account` has `comments` in its `prerequisites`, which is not in the `concepts` array of any other user-facing Concept Exercise:
+./config.json
+
+The …
```
> lint(track_config): check `prerequisites` and `concepts`

- src/lint/track_config.nim
With this commit, `configlet lint` now checks that a track-level
`config.json` file follows the below rules:
- The `exercises.concept[].concepts` values must not be in any other
concept exercise's `concepts` property
- The `exercises.concept[].concepts` values must match the
`concepts.slug` property of one of the concepts
- The `exercises.concept[].prerequisites` values must match the
`concepts.slug` property of one of the concepts
These rules currently apply to user-facing Concept Exercises only, which
are those with `status` of `active` or `beta`.
Refs: #386
---
Ping @iHiD - would you like another fast release for this one? Please sanity-check the below diff.
At the time of writing (`2021-09-05T18:14:00Z`), this PR produces the below diff to the output of `configlet lint`, per track: …
> lint(track_config): further check exercise concepts

- src/lint/track_config.nim
With this commit, `configlet lint` now checks that a track-level
`config.json` file follows the below rules for Concept Exercises:
- The `exercises.concept[].concepts` value must be a non-empty array of
strings if `exercises.concept[].status` is not equal to `deprecated`
- The `exercises.concept[].concepts` value must be an empty array if
`exercises.concept[].status` is equal to `deprecated`
- The `exercises.concept[].prerequisites` value must be a non-empty
array of strings if `exercises.concept[].status` is not equal to
`deprecated`, except for exactly one exercise which is allowed to have
an empty array as its value
- The `exercises.concept[].prerequisites` value must be an empty array
if `exercises.concept[].status` is equal to `deprecated`
and these rules for Practice Exercises:
- …
> lint(track_config): add more checks of `prerequisites`, `concepts`, `practices`

- src/lint/track_config.nim
With this PR, `configlet lint` now checks that a track-level
`config.json` file follows the below rules:
- The `exercises.concept[].slug` value must be unique in
`exercises.concept[].slug`  and may not exist in
`exercises.practice[].slug`
- The `exercises.practice[].slug` value must be unique in
`exercises.practice[].slug` and may not exist in
`exercises.concept[].slug`
- There must be exactly one `exercises.practice[].slug` value that is
the string `hello-world`
- The `exercises.foregone` values must not match any of the concept or
practice exercise slugs
---
At the time of writing (`2021-09-07T13:37:00Z`), this PR produces the following diff to the output of `configlet lint`, per track:
https://github.com/exercism/julia/blob/0a134640aeed/config.json#L102-L296
```diff
+The slug `leap` is …
```
> lint(track_config): add more checks of exercise slugs

- src/lint/track_config.nim
This PR:
- adds some comments that try to explain the approach for the second linting pass
- tries to improve an error message that a user shouldn't encounter.
Reproducing the latter commit message below.
---
Before this commit, an error during jsony's deserialization would look
something like:
```
jsony.nim(46)            parseHook
Error: unhandled exception: Expected " but got 1 instead. At offset: 73830 [JsonError]
```
With this commit, it instead looks like:
```
Error: JSON parsing error during the second linting pass:
config.json(3156, 10): Expected " but got 1 instead.
```
That is, we:
- Handle the exception
- Better explain what happened
- Mention the JSON file being parsed, rather than `jsony.nim`
- Provide the line and column number, rather than the offset, where the
parsing …
> lint(track_config): tidy up second pass

- src/helpers.nim
- src/lint/lint.nim
- src/lint/track_config.nim
With this PR, `configlet lint` now checks that a track-level
`config.json` file follows the below rules:
- The `exercises.practice[].prerequisites` values must match any
concept exercise's `exercises.concept[].concepts` values
- The `exercises.practice[].prerequisites` values must match the
`concepts[].slug` property of one of the concepts
- The `exercises.practice[].practices` values must match the
`concepts[].slug` property of one of the concepts
- The `exercises.practice[].practices` values must refer to an
individual concept's slug at most 10 times (across all exercises)
---
At the time of writing, this PR produces [this diff](https://gist.github.com/ee7/d7b3b2c1ba0db95a299eee3fd472604e) to the output of `configlet lint`, per track.
The diff is very large - bigger than the maximum …
> lint(track_config): add checks for Practice Exercise `practices` and `prerequisites`

- src/lint/track_config.nim
This PR currently causes the below diff to the output of `configlet lint`, per track:
```diff
+`./exercises/concept` contains a directory named `international-calling-connoisseur`, which is not a `slug` in the array of concept exercises:
+./config.json
+
+`./exercises/concept` contains a directory named `squeaky-clean`, which is not a `slug` in the array of concept exercises:
+./config.json
+
+Configlet detected at least one problem.
+For more information on resolving the problems, please see the documentation:
+https://github.com/exercism/docs/blob/main/building/configlet/lint.md
```
```diff
+`./exercises/concept` contains a directory named `the-farm`, which is not a `slug` in the array of concept exercises:
+./config.json
+
+Configlet detected at least one problem.
+For more information …
```
> lint(track_config): check exercise directories are slugs

- src/lint/track_config.nim
With the most recent configlet release (4.0.0-alpha.31), running
`configlet lint` using a directory that lacks a `config.json` file would
produce:
```
The lint command is under development.
Please re-run this command regularly to see if your track passes the latest linting rules.
Missing file:
/tmp/foo/config.json
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
With this commit, we get:
```
The lint command is under development.
Please re-run this command regularly to see if your track passes the latest linting rules.
Missing file:
/tmp/foo/config.json
Missing directory:
/tmp/foo/exercises/shared/.docs
Missing directory:
/tmp/foo/docs
Configlet detected at least one problem.
For more information on resolving the problems, please see the documentation: …
```
> lint(track_config): fix error for missing track config

- src/lint/track_config.nim
With this PR, `configlet lint` now produces an error if there is a subdirectory in the `concepts` directory of a track that does not have a corresponding entry in the track-level `config.json` file.
The implementation is similar to the exercise-based check.
See https://github.com/exercism/rust/pull/1363#issue-1022516101 CC @coriolinus
> lint(track_config): check concept directory names are in config

- src/sync/exercises.nim
- src/sync/probspecs.nim
This change is required for upgrading to Nim 1.6.0.
In Nim 1.4.x and Nim 1.6.0 rc2, compiling the below code with
`--experimental:strictFuncs` produces an error saying that `` `[]` `` has
side effects.
func getFooVal(j: JsonNode): JsonNode =
j["foo"]
However, in Nim 1.4.x, there was no error produced when similarly
compiling the below
type
MyNode = distinct JsonNode
proc `[]`(j: MyNode, name: string): MyNode {.borrow.}
func getFooVal(j: MyNode): MyNode =
j["foo"]
Nim 1.6.0 **does** produce an error in the latter case, so that the side
effect error is produced for using `` `[]` `` with both a `JsonNode` **and** a
`distinct JsonNode`.
This means we need to change some `func` to `proc` in our codebase,
because we use
ProbSpecsTestCase* = distinct JsonNode
and borrow the `` `[]` `` proc.
That …
> sync: change some `func` to `proc`

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
- src/patched_stdlib/json.nim
- src/patched_stdlib/parsejson.nim
This PR will fail until Nim 1.6.0 is actually released.
But RC1 is released - see https://forum.nim-lang.org/t/8404
> build: bump Nim from 1.4.8 to 1.6.0

- configlet.nimble
~The version of Nimble that's distributed with Nim does not yet support
lock files. But until it does, let's use the `==` operator in the
Nimble file as a lesser step in the right direction - pinning each
package to its most recent tag.~
~It's a lesser step because, unfortunately, a person with write access to
one of these dependencies could still theoretically tag a different
commit (potentially bad or malicious) with the tag specified here.~
~This commit pins each package to its latest tag, except `jsony`, which
we pin at 1.0.5 to avoid an error with its 1.1.0 release (2021-11-04).
Note that `isaac` is a dependency for the `uuids`.~
~This also fixes CI, which broke due to the jsony 1.1.0 release. See also~:
- ~https://github.com/ee7/jsony/commit/a46972034d94744cb6441a8fec251c22324cb4c3 …
> build: pin versions of Nimble packages

- README.md
- src/cli.nim
- src/configlet.nim
- src/fmt/fmt.nim
- src/sync/sync.nim
- src/sync/sync_common.nim
- src/sync/sync_filepaths.nim
- tests/all_tests.nim
- tests/test_fmt.nim
@ErikSchierboom what do you think about the interactivity here? Options:
1. `configlet fmt` prompts the user when the terminal is interactive (like `configlet sync`)
2. `configlet fmt` non-interactively formats.
For consistency with `configlet sync`, ~I did the latter~ (edit: I meant "I did option 1")
Ideally I'd have some "end-to-end" tests for this. But if you're happy, we can add them later.
To-do:
providing 'y' or 'yes' on stdin also works, like `echo 'y' | configlet fmt`
---
This commit adds the `fmt` command to configlet.
Running `configlet fmt` will print a list of paths for which there is
not already a formatted exercise `.meta/config.json` file, and write the
formatted files if the user confirms.
"Formatting" means:
- Write the key/value pairs in the canonical order.
- Use two …
> fmt: implement

- README.md
- src/cli.nim
Before this PR:
```
$ configlet --help
Usage:
configlet [global-options] <command> [command-options]
Commands:
fmt, lint, sync, uuid, generate, info
Options for fmt:
[...]
```
With this PR:
```
$ configlet --help
Usage:
configlet [global-options] <command> [command-options]
Commands:
fmt       Format the exercise 'meta/config.json' files
generate  Generate Concept Exercise 'introduction.md' files from 'introduction.md.tpl' files
info      Print some information about the track
lint      Check the track configuration for correctness
sync      Check or update Practice Exercise docs, metadata, and tests from 'problem-specifications'.
Check or populate missing 'files' values for Concept/Practice Exercises from the track 'config.json'.
uuid      Output new (version 4) UUIDs, suitable for the …
```
> cli, README: add command descriptions to help message

- src/sync/probspecs.nim
When performing an offline sync, and specifying a problem-specifications
directory that does not exist, e.g. via
```
$ configlet sync -o -p /foo/bar
```
before this commit, we would see this misleading message:
```
Checking exercises...
Every Practice Exercise has up-to-date docs, filepaths, metadata, and tests!
```
But with this commit, we see:
```
Checking exercises...
Error: the given problem-specifications directory does not exist: '/foo/bar'
```
Fixes: #74
> sync(probspecs): fix message for missing prob-specs dir

- src/info/info.nim
- src/info/prob_specs_slugs.txt
When running `configlet info`, the list of unimplemented exercises on a
track previously included exercises that are deprecated in
`problem-specifications`. With this commit, we show only
non-deprecated exercises.
Example output before this PR:
$ configlet info
[...]
There are 11 exercises from `exercism/problem-specifications` that are neither implemented nor in the track config `exercises.foregone` array:
counter
error-handling
hangman
ledger
lens-person
nucleotide-codons
octal
paasio
point-mutations
tree-building
trinary
[...]
With this PR:
$ configlet info
[...]
There are 6 non-deprecated exercises in `exercism/problem-specifications` that
are both unimplemented and not in the track config `exercises.foregone` array:
error-handling
hangman
ledger
lens-person
paasio
tree-building
[...] …
> info: omit deprecated exercises

- .github/workflows/build.yml
- .github/workflows/tests.yml
- config.nims
- configlet.nimble
- src/patched_stdlib/json.nim
See:
- https://nim-lang.org/blog/2021/12/17/version-162-released.html
- https://github.com/nim-lang/Nim/compare/v1.6.0...version-1-6
- https://forum.nim-lang.org/t/8717
Nim 1.6.2 supports Nimble 0.14 (which supports lockfiles) but does not ship with it.
If we want to merge #418 without waiting for Nim to release with that Nimble version, we'll have to install that Nimble ourselves in the build environment.
Please compare with the previous Nim version bump: https://github.com/exercism/configlet/pull/419
The CI failure seems like a regression in `strictEffects` with Nim 1.6.2. I've reported it upstream.
> build: bump Nim from 1.6.0 to 1.6.2

- .github/bin/publish-release
Even after commit a103ac4607d9, three draft releases were created during
the latest release build.
It looks like the flaw was that `gh release view` returns the latest
non-draft release, and so `gh release create --draft` always ran.
Fixes: #484
---
This time, I tested it better. It seems to work here: https://github.com/ee7/exercism-configlet/releases/tag/untagged-820ff06a337a5d420c03
It seems that `gh release view foo` returns an exit code of 0 when there is a draft release or release with the tag `foo`, and an exit code of 1 otherwise.
> github: create only one draft release

- README.md
#462 included some markdown linting, but commits 1fd2a46fddfb and 4a88c133fe98 added a lot to the repo `README.md`, and introduced some markdown issues.
Let's fix these markdown issues in this PR, then rebase that PR on top.
Resolved `markdownlint` rule violations:
- [MD014](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md014)
- [MD040](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md040)
- [MD032](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md032)
- [MD034](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md034)
> README: lint

- src/lint/track_config.nim
We were using [concatenation of two sequences](https://github.com/nim-lang/Nim/blob/b812431f8317/lib/system.nim#L1672-L1686):
```Nim
proc `&`*[T](x, y: seq[T]): seq[T] {.noSideEffect.} =
newSeq(result, x.len + y.len)
for i in 0..x.len-1:
result[i] = x[i]
for i in 0..y.len-1:
result[i+x.len] = y[i]
```
but we can use [the overload that appends one element](https://github.com/nim-lang/Nim/blob/b812431f8317/lib/system.nim#L1688-L1701):
```Nim
proc `&`*[T](x: seq[T], y: T): seq[T] {.noSideEffect.} =
newSeq(result, x.len + 1)
for i in 0..x.len-1:
result[i] = x[i]
result[x.len] = y
```
The Nim compiler doesn't optimize the creation+appending of a
one-element sequence into an append of the element. Somewhat similarly,
the compiler deliberately doesn't optimize `string1 = string1 & string2` -
it …
> lint(track_config): speedup cycle checking slightly

- src/lint/lint.nim
We set a deadline of October 2021 for turning these warnings into errors, but we didn't act on it. Quite a few tracks still have some work to do.
Let's give tracks a little more time to address these warnings.
---
At the time of writing, there are 10 tracks for which `configlet lint` produces a warning: 
<details>
<summary>csharp</summary>
```
The lint command is under development.
Please re-run this command regularly to see if your track passes the latest linting rules.
Warning: The following concepts exist in the `practices` array of a Practice Exercise in `./csharp/config.json`, but do not exist in the top-level `concepts` array
linq
queues
stacks
multi-dimensional-arrays
streams
lazy-evaluation
recursion
yield
generic-methods
foreach
immutability
higher-order-functions
parallellism …
```
> lint: extend deadline for turning warnings into errors

- README.md
This commit only adds newlines. It doesn't change how the document is
rendered, but it makes diffs more obvious.
> README: use one line per sentence

- src/lint/lint.nim
The previous message implied that running `configlet lint` without
updating `configlet` would use the latest linting rules.
> lint: clarify message about updating configlet

- tests/test_binary.nim
This ensures that we update the repo README after the `configlet --help`
message changes.
Closes: #73
> tests(binary): test that README contains help message

- README.md
- src/cli.nim
This removes potential for confusion with `configlet generate`.
---
A bit nitpick-y, but worthwhile?
Another reason: if `configlet uuid` is ever updated to just "read" from a system UUID provider (see #424), we might say that it no longer "generates" the UUIDs.
> cli: avoid the word "generate" in uuid help text

- src/cli.nim
Before this commit, the name of the executable in the help message was
set at execution time. That is, renaming the configlet executable to
`foo` and then running `foo --help` would produce a help message that
begins:
Usage:
foo [global-options] <command> [command-options]
We don't need to support this, so let's set the name of the application
at compile time. This saves a call to `getAppFilename`, and makes it
cleaner to add a short description of configlet to the top of the help
message in the future.
---
This commit doesn't change the help message under normal circumstances (as shown by the test added in 8b67417667e9).
> cli: set help text at compile time

- src/cli.nim
- tests/test_binary.nim
The help message was missing a description of what configlet does.
The help message in the configlet for Exercism v2 began like:
```console
$ ./configlet --help
./configlet version 3.9.2
A tool for managing Exercism language track repositories.
Usage:
./configlet [command]
[...]
```
> cli: add configlet description to help text

- src/cli.nim
Refactoring only.
The main improvement is 67927847db08 - we no longer need to specify the commands that take options.
> cli: refactor help message construction

- src/cli.nim
- src/sync/exercises.nim
- src/sync/probspecs.nim
- src/sync/sync.nim
- src/sync/tracks.nim
- tests/test_probspecs.nim
- tests/test_tracks.nim
This commit makes our object construction style in older code consistent with the style that I used in the newer sync code (1fd2a46fddfb):
https://github.com/exercism/configlet/blob/9296b431572af4306e07b0a0696e5813204f17e4/src/sync/sync.nim#L40-L44
https://github.com/exercism/configlet/blob/9296b431572af4306e07b0a0696e5813204f17e4/src/sync/sync_filepaths.nim#L78-L88
People have differing opinions on Nim object construction style (and I haven't fully got used to the style in this PR myself) but this is at least more DRY. One advantage is for refactoring: if you want to rename a type from `Foo` to `Bar`, you no longer also need to rename the constructor from `initFoo` to `initBar`.
With this PR, we use the `Foo.init` and `Foo.new` style everywhere (excluding the patched `json.nim` and …
> prefer `Foo.init` object construction style

- src/helpers.nim
- src/lint/validators.nim
This PR adds support for linting errors to also print an annotation,
which can be used to give more detailed information on a certain
linting rule validation error.
For example, the following is now printed when the `tags` key in the
track's `config.json` file does not validate:
```
The `tags` array is empty:
../csharp/config.json
Tracks are annotated with tags to allow searching for tracks with certain tags.
The tags should be chosen based on the general usage of their language.
For more information and the full list of supported tags see:
https://exercism.org/docs/building/tracks/config-json#h-tags
```
Note that the first line ("The `tags` array is empty:") is output in the color red, while the annotation lines are printed in yellow.
> lint: support error annotations

- .github/workflows/build.yml
- .github/workflows/tests.yml
- configlet.nimble
~Creating this in advance.~
~1.6.4 rc1 was released - see https://forum.nim-lang.org/t/8839~
~CI is expected to fail until it's actually released.~
---
See:
- Blog post: https://nim-lang.org/blog/2022/02/08/version-164-released.html
- Forum post: https://forum.nim-lang.org/t/8887
- Changes: https://github.com/nim-lang/Nim/compare/v1.6.2...v1.6.4 (no changes in `json.nim` or `parsejson.nim` for us to port)
Previous Nim bump PR: #480
> build: bump Nim from 1.6.2 to 1.6.4

- src/lint/track_config.nim
- src/lint/validators.nim
- lint: allow overlap of `files.example` and `files.exemplar` values
- lint: allow overlap of solution and test files for `d` and `plsql` tracks
See https://github.com/exercism/docs/pull/321/files
> Allow file pattern overlap exceptions

- src/lint/lint.nim
Better to link to exercism.org everywhere, I guess?
Follow-up from https://github.com/exercism/configlet/pull/517#pullrequestreview-884706384
> lint: link to docs on exercism.org, not GitHub

- src/lint/track_config.nim
- src/lint/validators.nim
- validation: allow printing an annotation for error message
- validation: allow passing an error annotation to validation functions
- lint: add annotation for tags in config.json
> lint: add error annotations for tags and key features
